### ISSUE TITLE
0.4rc1: FITSFigure

### ISSUE THREAD

**Issue by adeleplunkett** [astropy/astropy#2714]
I recently updated astropy (naively trying to use a new feature), but when I ran a familiar command that worked with the previous version, it gave an error.  I went back to astropy 0.3.2, and the command worked again.  Might be worth checking whether it can work in 0.4rc1, or it's a problem on my end.  Thanks!  Below is the update I did, and the error I got for aplpy.FITSFigure .  Keep in mind, I'm not an astropy pro.

<pre>$ conda update astropy
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /Users/Adele/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    astropy-0.4rc1             |       np18py27_0         4.9 MB
    python-2.7.8               |                0         9.8 MB
    ------------------------------------------------------------
                                           Total:        14.8 MB

The following packages will be UN-linked:

    package                    |            build
    ---------------------------|-----------------
    astropy-0.3.2              |       np18py27_0
    python-2.7.7               |                2

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    astropy-0.4rc1             |       np18py27_0   hard-link
    python-2.7.8               |                0   hard-link
</pre>

Then, in python, I ran this command, and got an error:

<pre>
>> In [7]: gc2 = aplpy.FITSFigure(array_in,figure=fig2) 
INFO: Setting slices=[0, 0] [aplpy.aplpy]
ERROR: AttributeError: type object 'WCS' has no attribute 'wcs_pix2sky' [aplpy.wcs_util]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-a0ce41094fbb> in <module>()
----> 1 gc2 = aplpy.FITSFigure(array_in,figure=fig2) #subplot to match add_subplot defaults

/Users/Adele/anaconda/lib/python2.7/site-packages/aplpy/aplpy.pyc in __init__(self, data, hdu, figure, subplot, downsample, north, convention, dimensions, slices, auto_refresh, **kwargs)

/Users/Adele/anaconda/lib/python2.7/site-packages/aplpy/decorators.pyc in _auto_refresh(f, *args, **kwargs)
     23     mydata.nesting = getattr(mydata, 'nesting', 0) + 1
     24     try:
---> 25         f(*args, **kwargs)
     26     finally:
     27         mydata.nesting -= 1

/Users/Adele/anaconda/lib/python2.7/site-packages/aplpy/aplpy.pyc in __init__(self, data, hdu, figure, subplot, downsample, north, convention, dimensions, slices, auto_refresh, **kwargs)
    241         else:
    242             self._data, self._header, self._wcs = self._get_hdu(data, hdu, north, \
--> 243                 convention=convention, dimensions=dimensions, slices=slices)
    244             self._wcs.nx = self._header['NAXIS%i' % (dimensions[0] + 1)]
    245             self._wcs.ny = self._header['NAXIS%i' % (dimensions[1] + 1)]

/Users/Adele/anaconda/lib/python2.7/site-packages/aplpy/aplpy.pyc in _get_hdu(***failed resolving arguments***)
    409
    410         # Parse WCS info
--> 411         wcs = wcs_util.WCS(header, dimensions=dimensions, slices=slices, relax=True)
    412
    413         return data, header, wcs

/Users/Adele/anaconda/lib/python2.7/site-packages/aplpy/wcs_util.pyc in __init__(self, *args, **kwargs)
     51                     s += 1
     52             coords = np.vstack(coords).transpose()
---> 53             result = AstropyWCS.wcs_pix2sky(self, coords, 1)
     54             self._mean_world = np.mean(result, axis=0)
     55             # result = result.transpose()

AttributeError: type object 'WCS' has no attribute 'wcs_pix2sky'</pre>
