### ISSUE TITLE
Creating docs using "make html" fails

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10137]
I'm having trouble building the docs; using `tox`, it just fails more or less outright, for reasons that may have to do with the way Debian sets things up (will try to raise a separate issue), but even the nominal way using `make html` fails, with what at least seems to be something that would be easier to fix:

```
pip install .[docs]
cd docs
make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.8.5

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/mhvk/data/mhvk/packages/astropy/docs/conf.py", line 91, in <module>
    rst_epilog += """
AttributeError: module 'astropy' has no attribute '__minimum_scipy_version__'
```

If I replace the `{0.__minimum_scipy_version__}` in https://github.com/astropy/astropy/blob/b505c4b5d9b673adf5b756208ed30cd1f02608dd/docs/conf.py#L94 with some text, `make html` does work.

**Comment by pllim** [comment]
Your Sphinx is too old? I think it is 2.x now.

**Comment by bsipocz** [comment]
As I see we haven't yet bumped the required mininum version, it's still 1.7. 

However that's ancient, so I'm 💯 for bumping it if it solves this issue.

**Comment by mhvk** [comment]
Debian/testing has sphinx 1.8.5, which was released 2019 March 10, so just a year ago. But I'll check whether that is in fact the problem...

**Comment by mhvk** [comment]
Hmm, it is not a sphinx version thing, but somehow related to my Debian installation - things only do not work when I use `--system-site-packages` (it works fine with sphinx==1.8.5 in a clean venv). I have noticed this before and it is unfortunate, as it used to work fine, but clearly this is not directly an astropy issue, so I'll close.
