### ISSUE TITLE
Sphinx Travis build reoccuring problem: cannot import read_table_hdf5

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#6604]
There's a failure I've been seeing regularly with sphinx that doesn't seem to depend on flaky internet problems:

```
Exception occurred:
  File "/home/travis/build/astropy/astropy/build/lib.linux-x86_64-3.6/astropy/io/misc/connect.py", line 6, in <module>
    from .hdf5 import read_table_hdf5, write_table_hdf5, is_hdf5
ImportError: cannot import name 'read_table_hdf5'
```

Unfortunately I don't have any log for astropy but I have one on my local fork: https://travis-ci.org/MSeifert04/astropy/jobs/279343905#L2495

**Comment by MSeifert04** [comment]
okay, it also just happened on a PR: https://travis-ci.org/astropy/astropy/jobs/279463524#L2505

**Comment by saimn** [comment]
And it happens also on rtd: http://readthedocs.org/projects/astropy/builds/6014269/
It would be useful to have a full log.

**Comment by drdavella** [comment]
Here's another data point, FWIW: https://travis-ci.org/astropy/astropy/jobs/279610210

**Comment by pllim** [comment]
I can actually reproduce this locally on Python 3.6 env. I suspect circular import. Investigating.

**Comment by MSeifert04** [comment]
Even after merging #6607 the error persists:

```
Exception occurred:
  File "/home/travis/build/astropy/astropy/build/lib.linux-x86_64-3.6/astropy/io/misc/connect.py", line 8, in <module>
    from .hdf5 import read_table_hdf5, write_table_hdf5, is_hdf5
ImportError: cannot import name 'read_table_hdf5'
```

Given that it reports line 8 it seems like it has picked up the change but still failed.

**Comment by pllim** [comment]
@astrofrog , since you are listed for `io.misc`, can I move the functions from `hdf5.py` to `connect.py`?

**Comment by astrofrog** [comment]
My worry is that ``connect.py`` might then have several file formats in it. What about instead regisetring the functions inside ``hdf5.py`` - would that work?

**Comment by MSeifert04** [comment]
I think it's reproducible: in a fresh interpreter try `from astropy.io.misc import hdf5`. That does fail with the encountered message.
