### PR TITLE
Fix extension conf when using system libraries

### LINKED ISSUE #10534: 4.1rc1: Numpy headers not found when using system cfitsio or wcslib
I am trying to prepare the openSUSE package for the next release, [working with 4.1rc1](https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:numeric/python-astropy-rc).

I am running into compilation errors when trying to unbundle cfitsio and wcslib. Some subpackages do not find the numpy headers. The proper include parameter for gcc is missing:

With `ASTROPY_USE_SYSTEM_CFITSIO=1`:
```
...
[   35s] building 'astropy.io.ascii.cparser' extension
[   35s] creating build/temp.linux-x86_64-3.8/astropy/io
[   35s] creating build/temp.linux-x86_64-3.8/astropy/io/ascii
[   35s] creating build/temp.linux-x86_64-3.8/astropy/io/ascii/src
[   35s] gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -fPIC -I/usr/lib64/python3.8/site-packages/numpy/core/include -I/usr/include/python3.8 -c astropy/io/ascii/cparser.c -o build/temp.linux-x86_64-3.8/astropy/io/ascii/cparser.o
...
[   46s] building 'astropy.io.fits.compression' extension
[   46s] creating build/temp.linux-x86_64-3.8/astropy/io/fits
[   46s] creating build/temp.linux-x86_64-3.8/astropy/io/fits/src
[   46s] gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -fPIC -U_REENTRANT -I/usr/include/cfitsio -I/usr/include/python3.8 -c ./astropy/io/fits/src/compressionmodule.c -o build/temp.linux-x86_64-3.8/./astropy/io/fits/src/compressionmodule.o
[   46s] ./astropy/io/fits/src/compressionmodule.c:100:10: fatal error: numpy/arrayobject.h: No such file or directory
[   46s]   100 | #include <numpy/arrayobject.h>
[   46s]       |          ^~~~~~~~~~~~~~~~~~~~~
[   46s] compilation terminated.
```
Note that  `astropy.io.ascii.cparser`  has the `-I...numpy..` parameter,  `astropy.io.fits.compression` does not.

With `ASTROPY_USE_SYSTEM_WCSLIB=1`:
```
[   10s] building 'astropy.convolution._convolve' extension
[   10s] creating build/temp.linux-x86_64-3.8
[   10s] creating build/temp.linux-x86_64-3.8/astropy
[   10s] creating build/temp.linux-x86_64-3.8/astropy/convolution
[   10s] creating build/temp.linux-x86_64-3.8/astropy/convolution/src
[   10s] gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -fPIC -I/usr/lib64/python3.8/site-packages/numpy/core/include -I/usr/include/python3.8 -c astropy/convolution/src/convolve.c -o build/temp.linux-x86_64-3.8/astropy/convolution/src/convolve.o -UNDEBUG -fPIC
[   10s] gcc -pthread -shared build/temp.linux-x86_64-3.8/astropy/convolution/src/convolve.o -L/usr/lib64 -o build/lib.linux-x86_64-3.8/astropy/convolution/_convolve.cpython-38-x86_64-linux-gnu.so
[   10s] building 'astropy.modeling._projections' extension
[   10s] creating build/temp.linux-x86_64-3.8/astropy/modeling
[   10s] creating build/temp.linux-x86_64-3.8/astropy/modeling/src
[   10s] gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -fPIC -DECHO -DWCSTRIG_MACRO -DASTROPY_WCS_BUILD -D_GNU_SOURCE -DNDEBUG -DHAVE_SINCOS -UDEBUG -I/usr/include/wcslib -Iastropy/modeling/src -I/usr/include/python3.8 -c astropy/modeling/src/projections.c -o build/temp.linux-x86_64-3.8/astropy/modeling/src/projections.o -Wno-strict-prototypes -Wno-unused-function -Wno-unused-value -Wno-uninitialized
[   10s] astropy/modeling/src/projections.c:12:10: fatal error: numpy/arrayobject.h: No such file or directory
[   10s]    12 | #include <numpy/arrayobject.h> /* Numpy */
[   10s]       |          ^~~~~~~~~~~~~~~~~~~~~
[   10s] compilation terminated.

```
In this case these are the first two extensions to be compiled, the first one has the numpy header include parameter, the second does not.

This does not happen when the bundled cfitsio and wcslib are used.

### System Details
(See the logs from the linked OBS project above for the whole system environment and used package versions)

```
[    4s] Linux-5.7.5-1-default-x86_64-with-glibc2.2.5
[    4s] Python 3.8.3 (default, May 17 2020, 14:48:56) [GCC]
[    4s] Numpy 1.18.4
[    4s] astropy n/a
[    4s] Scipy n/a
[    4s] Matplotlib n/a
```

### PR DESCRIPTION
**Pull request by saimn**
Fix #10534 : compiler arguments from `pkg_config` were overwriting the options already defined, e.g. `include_dirs`.

Not sure if this needs a changelog entry, I think this issue came with the helpers change in 4.1 ?

### CODE REVIEW

**Comment by saimn** [comment]
I don't think any build test this so I cancelled builds.

**Comment by pllim** [comment]
Thanks, @saimn ! cc @bnavigator

**Comment by bnavigator** [comment]
The build itself is successful.

I now get a bunch of wcslib related unit test failures:

https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:numeric/python-astropy-rc?rev=12

[python-astropy-4.1rc1_test_x86_64_log.txt](https://github.com/astropy/astropy/files/4887023/python-astropy-4.1rc1_test_x86_64_log.txt)
```
[  154s] + pytest-3.8 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v --ignore docs/whatsnew
[  156s] Internet access disabled
[  156s] ============================= test session starts ==============================
[  156s] platform linux -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
[  156s] cachedir: .pytest_cache
[  156s] Matplotlib: 3.2.2
[  156s] Freetype: 2.10.2
[  156s] hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/abuild/rpmbuild/BUILD/astropy-4.1rc1/.hypothesis/examples')
[  156s] 
[  156s] Running tests with Astropy version 4.1rc1.
[  156s] Running tests in astropy docs.
[  156s] 
[  156s] Date: 2020-07-07T19:58:01
[  156s] 
[  156s] Platform: Linux-5.7.5-1-default-x86_64-with-glibc2.2.5
[  156s] 
[  156s] Executable: /usr/bin/python3
[  156s] 
[  156s] Full Python Version: 
[  156s] 3.8.3 (default, May 17 2020, 14:48:56) [GCC]
[  156s] 
[  156s] encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
[  156s] byteorder: little
[  156s] float info: dig: 15, mant_dig: 15
[  156s] 
[  156s] Package versions: 
[  156s] Numpy: 1.18.4
[  156s] Scipy: 1.4.1
[  156s] Matplotlib: 3.2.2
[  156s] h5py: 2.10.0
[  156s] Pandas: 1.0.5
[  156s] PyERFA: 4.1rc1
[  156s] 
[  156s] Using Astropy options: remote_data: none.
[  156s] 
[  156s] rootdir: /home/abuild/rpmbuild/BUILD/astropy-4.1rc1, inifile: setup.cfg, testpaths: astropy, docs
[  156s] plugins: remotedata-0.3.2, filter-subpackage-0.0.0, arraydiff-0.3, mpl-0.11, openfiles-0.5.0, doctestplus-0.7.0, hypothesis-5.11.0, astropy-header-0.1.2, asdf-2.6.0, cov-2.10.0
[  205s] collecting ... collected 15300 items / 2 skipped / 15298 selected
...
[  863s] =========================== short test summary info ============================
[  863s] FAILED astropy/nddata/tests/test_ccddata.py::test_wcs_attribute - assert None...
[  863s] FAILED astropy/wcs/tests/test_wcs.py::test_dict_init - AssertionError: No 'da...
[  863s] FAILED astropy/wcs/tests/test_wcs.py::test_to_header_string - AssertionError:...
[  863s] FAILED astropy/wcs/tests/test_wcs.py::test_to_fits - AssertionError: assert W...
[  863s] FAILED astropy/wcs/tests/test_wcs.py::test_list_naxis - AssertionError: No 'd...
[  863s] FAILED astropy/wcs/tests/test_wcs.py::test_no_truncate_using_compare - astrop...
[  863s] FAILED astropy/wcs/tests/test_wcs.py::test_inconsistent_sip - AssertionError:...
[  863s] FAILED astropy/wcs/tests/test_wcs.py::test_sip_with_altkey - AssertionError: ...
[  863s] FAILED astropy/wcs/tests/test_wcsprm.py::test_fix2 - assert {'cdfix': 'No...-...
[  863s] FAILED astropy/wcs/tests/test_wcsprm.py::test_fix3 - assert {'cdfix': 'No.../...
[  863s] FAILED astropy/wcs/tests/test_wcsprm.py::test_datebeg - assert {'cdfix': 'No....
[  863s] FAILED astropy/wcs/tests/test_wtbarr.py::test_wtbarr_print - AssertionError: ...
[  863s] ==== 12 failed, 14849 passed, 387 skipped, 54 xfailed in 707.46s (0:11:47) =====
```

**Comment by pllim** [comment]
@bnavigator , what is your wcslib version?

**Comment by bnavigator** [comment]
7.3: https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:numeric/wcslib

I am looking into the errors right now. Seems to be related to #10433

**Comment by pllim** [comment]
Looks like there is a temporary commit, so I'll let you merge when you think it is ready, @saimn .

**Comment by saimn** [comment]
@pllim - Yes, I pushed something to test building with system libraries on Travis.

**Comment by saimn** [comment]
Hum there is an unrelated failure with colorama, and the cron job is failing for the same reason, e.g. https://travis-ci.org/github/astropy/astropy/builds/705844034
So I will revert the test changes for now.

**Comment by pllim** [comment]
Re: unrelated failure -- Maybe @mhvk knows why colorama is failing, but we can punt it off to #10539
