### ISSUE TITLE
TST: New failures in "numpy-dev" job?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7214]
I don't see how these are related to the `einsum` thingy that is known. Example: https://travis-ci.org/astropy/astropy/jobs/342443502

```
_________________________________ test__str__ __________________________________
        # non-scalar array angles
        arrangle = Angle(['10.2345d', '-20d'])
>       strarrangle = arrangle.__str__()
astropy/coordinates/tests/test_angles.py:861: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = 10.2345
>   return np.array2string(self, formatter={'all': lambda x: x.to_string()})
E   AttributeError: 'numpy.float64' object has no attribute 'to_string'
astropy/coordinates/angles.py:433: AttributeError
```

```
_______________________________ test_repr_latex ________________________________
        # and array angles
        arrangle = Angle([1, 2.1], u.deg)
>       rlarrangle = arrangle._repr_latex_()
astropy/coordinates/tests/test_angles.py:880: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = 1.0
>   return np.array2string(self, formatter={'all': lambda x: x.to_string(format='latex')})
E   AttributeError: 'numpy.float64' object has no attribute 'to_string'
astropy/coordinates/angles.py:441: AttributeError
```

```
______________________ TestTableFunctions.test_mask_array ______________________
        expect = r"\[\('NGC1002',\s+12.3[0-9]*\) \(\'NGC1003\',\s+15.[0-9]+\)\]"
>       assert re.match(expect, str(hdu.data))
E       assert None
E        +  where None = <function match at 0x7f9c2068fe18>("\\[\\('NGC1002',\\s+12.3[0-9]*\\) \\(\\'NGC1003\\',\\s+15.[0-9]+\\)\\]", "[(b'NGC1002', 12.3) (b'NGC1003', 15.2)]")
E        +    where <function match at 0x7f9c2068fe18> = re.match
E        +    and   "[(b'NGC1002', 12.3) (b'NGC1003', 15.2)]" = str(FITS_rec([(b'NGC1002', 12.3), (b'NGC1003', 15.2)],\n         dtype=(numpy.record, [('target', 'S20'), ('V_mag', '>f4')])))
E        +      where FITS_rec([(b'NGC1002', 12.3), (b'NGC1003', 15.2)],\n         dtype=(numpy.record, [('target', 'S20'), ('V_mag', '>f4')])) = <astropy.io.fits.hdu.table.BinTableHDU object at 0x7f9bb7bf6438>.data
astropy/io/fits/tests/test_table.py:860: AssertionError
```

```
_____________________ [doctest] docs/coordinates/index.rst _____________________
248 :func:`astropy.coordinates.EarthLocation.get_site_names`.
249 
250 For arbitrary Earth addresses (e.g., not observatory sites), use the
251 `~astropy.coordinates.EarthLocation.of_address` classmethod. Any address passed
252 to this function uses Google maps to retrieve the latitude and longitude and can
253 also (optionally) query Google maps to get the height of the location. As with
254 Google maps, this works with fully specified addresses, location names, city
255 names, and etc.::
256 
257     >>> EarthLocation.of_address('1002 Holy Grail Court, St. Louis, MO')  # doctest: +REMOTE_DATA +FLOAT_CMP
Expected:
    <EarthLocation (-26726.98216371, -4997009.8604809, 3950271.16507911) m>
Got:
    <EarthLocation (-26724.93406367, -4997006.87829221, 3950274.92599205) m>
/tmp/astropy-test-eem6lc45/lib/python3.6/site-packages/docs/coordinates/index.rst:257: DocTestFailure
```

```
_________________ [doctest] docs/io/fits/usage/unfamiliar.rst __________________
020 same, i.e. the data is in the ``.data`` attribute and the ``field()`` method
021 is used to refer to the columns and returns a numpy array. When reading the
022 table, Astropy will automatically detect what kind of table it is.
023 
024 ::
025 
026     >>> from astropy.io import fits
027     >>> filename = fits.util.get_testdata_filepath('ascii.fits')
028     >>> hdul = fits.open(filename)
029     >>> hdul[1].data[:1]  # doctest: +FLOAT_CMP
Expected:
    FITS_rec([(10.123, 37)],
             dtype=(numpy.record, {'names':['a','b'], 'formats':['S10','S5'], 'offsets':[0,11], 'itemsize':16}))
Got:
    FITS_rec([(b'.10123E+02', b'   37')],
             dtype=(numpy.record, {'names':['a','b'], 'formats':['S10','S5'], 'offsets':[0,11], 'itemsize':16}))
/tmp/astropy-test-eem6lc45/lib/python3.6/site-packages/docs/io/fits/usage/unfamiliar.rst:29: DocTestFailure
```

**Comment by lupinix** [comment]
I also see that on Fedora, our builds are failing with that issue after numpy 1.14.1 has been imported.

**Comment by lupinix** [comment]
```>=================================== FAILURES ===================================
>_________________________________ test__str__ __________________________________
>   def test__str__():
>        """
>        Check the __str__ method used in printing the Angle
        """
    
        # scalar angle
        scangle = Angle('10.2345d')
        strscangle = scangle.__str__()
        assert strscangle == '10d14m04.2s'
    
        # non-scalar array angles
        arrangle = Angle(['10.2345d', '-20d'])
>       strarrangle = arrangle.__str__()
astropy/coordinates/tests/test_angles.py:864: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/coordinates/angles.py:437: in __str__
    return np.array2string(self, formatter={'all': lambda x: x.to_string()})
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:629: in array2string
    return _array2string(a, options, separator, prefix)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:426: in wrapper
    return f(self, *args, **kwargs)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:460: in _array2string
    summary_insert, options['legacy'])
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:757: in _formatArray
    curr_width=line_width)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:711: in recurser
    word = recurser(index + (-i,), next_hanging_indent, next_width)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:665: in recurser
    return format_function(a[index])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = 10.2345
>   return np.array2string(self, formatter={'all': lambda x: x.to_string()})
E   AttributeError: 'numpy.float64' object has no attribute 'to_string'
astropy/coordinates/angles.py:437: AttributeError
_______________________________ test_repr_latex ________________________________
    def test_repr_latex():
        """
        Check the _repr_latex_ method, used primarily by IPython notebooks
        """
    
        # try with both scalar
        scangle = Angle(2.1, u.deg)
        rlscangle = scangle._repr_latex_()
    
        # and array angles
        arrangle = Angle([1, 2.1], u.deg)
>       rlarrangle = arrangle._repr_latex_()
astropy/coordinates/tests/test_angles.py:883: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/coordinates/angles.py:445: in _repr_latex_
    return np.array2string(self, formatter={'all': lambda x: x.to_string(format='latex')})
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:629: in array2string
    return _array2string(a, options, separator, prefix)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:426: in wrapper
    return f(self, *args, **kwargs)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:460: in _array2string
    summary_insert, options['legacy'])
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:757: in _formatArray
    curr_width=line_width)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:711: in recurser
    word = recurser(index + (-i,), next_hanging_indent, next_width)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:665: in recurser
    return format_function(a[index])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = 1.0
>   return np.array2string(self, formatter={'all': lambda x: x.to_string(format='latex')})
E   AttributeError: 'numpy.float64' object has no attribute 'to_string'
astropy/coordinates/angles.py:445: AttributeError
_________________________________ test__str__ __________________________________
    def test__str__():
        """
        Check the __str__ method used in printing the Angle
        """
    
        # scalar angle
        scangle = Angle('10.2345d')
        strscangle = scangle.__str__()
        assert strscangle == '10d14m04.2s'
    
        # non-scalar array angles
        arrangle = Angle(['10.2345d', '-20d'])
>       strarrangle = arrangle.__str__()
astropy/coordinates/tests/test_angles.py:864: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/coordinates/angles.py:437: in __str__
    return np.array2string(self, formatter={'all': lambda x: x.to_string()})
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:629: in array2string
    return _array2string(a, options, separator, prefix)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:426: in wrapper
    return f(self, *args, **kwargs)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:460: in _array2string
    summary_insert, options['legacy'])
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:757: in _formatArray
    curr_width=line_width)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:711: in recurser
    word = recurser(index + (-i,), next_hanging_indent, next_width)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:665: in recurser
    return format_function(a[index])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = 10.2345
>   return np.array2string(self, formatter={'all': lambda x: x.to_string()})
E   AttributeError: 'numpy.float64' object has no attribute 'to_string'
astropy/coordinates/angles.py:437: AttributeError
_______________________________ test_repr_latex ________________________________
    def test_repr_latex():
        """
        Check the _repr_latex_ method, used primarily by IPython notebooks
        """
    
        # try with both scalar
        scangle = Angle(2.1, u.deg)
        rlscangle = scangle._repr_latex_()
    
        # and array angles
        arrangle = Angle([1, 2.1], u.deg)
>       rlarrangle = arrangle._repr_latex_()
astropy/coordinates/tests/test_angles.py:883: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/coordinates/angles.py:445: in _repr_latex_
    return np.array2string(self, formatter={'all': lambda x: x.to_string(format='latex')})
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:629: in array2string
    return _array2string(a, options, separator, prefix)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:426: in wrapper
    return f(self, *args, **kwargs)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:460: in _array2string
    summary_insert, options['legacy'])
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:757: in _formatArray
    curr_width=line_width)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:711: in recurser
    word = recurser(index + (-i,), next_hanging_indent, next_width)
/usr/lib64/python2.7/site-packages/numpy/core/arrayprint.py:665: in recurser
    return format_function(a[index])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = 1.0
>   return np.array2string(self, formatter={'all': lambda x: x.to_string(format='latex')})
E   AttributeError: 'numpy.float64' object has no attribute 'to_string'
astropy/coordinates/angles.py:445: AttributeError```

**Comment by astrofrog** [comment]
@mhvk - are you familiar with the failures with Numpy 1.14.1?

**Comment by mhvk** [comment]
Possibly https://github.com/numpy/numpy/pull/10544. I'll try to see if a work-around is possible. Sorry to have missed this before numpy 1.14.1 was release; now we have yet more incompatibility.

**Comment by eric-wieser** [comment]
It's not clear to me that that's the cause - it's the non-0d cases that are failing here, and they don;t seem to be recursing to the 0d case either.

**Comment by mhvk** [comment]
@eric-wieser - The problem is the `a = asarray(a)` that was introduced. Our code relies on indexing to return an item of the same class, not a scalar.

**Comment by mhvk** [comment]
Ideally, this can be fixed upstream, but since it would be good to be able to work with numpy 1.14.1, a fix from our side in #7234.

**Comment by pllim** [comment]
Update: Both Travis and Appveyor CIs are picking up these failures as they use Numpy 1.14.1. Hopefully they can be cleared soon. All the CI badges on repo README are red currently. :cry:

**Comment by saimn** [comment]
I had a look at the fits failures. It seems that arrayprint no more calls `FITS_rec.__getitem__`, so this skips the conversion done of columns (e.g. decoding to unicode). Maybe related to https://github.com/numpy/numpy/pull/10612 which removed `StructureFormat` (which was calling `FITS_rec.__getitem__` with its format functions). cc @mhvk as you probably have a better understanding of this.

**Comment by astrofrog** [comment]
Just for info, @mhvk has started to fix some of these in https://github.com/astropy/astropy/pull/7234 but there are still a couple of failures.

**Comment by saimn** [comment]
Yep, I saw this, but now that I read https://github.com/numpy/numpy/issues/10663 it seems to be the same issue (*" In particular, astropy's Angle class assumed that inside array2print, any item selection would be done using its __getitem__, so that even scalars would be returned as array scalars with all the appropriate methods. "*).

**Comment by mhvk** [comment]
@saimn - I had just started to look at this too, and come to the same conclusion: the `__getitem__` is missed here because of the `asarray`. In this case, it is more annoying to fix than for `Angle` since we don't call `array2string` directly with a format function of our own, and thus have to do more work. I think this will be fixed in 1.14.2, and since the `FITS_rec` regression does not break anything (unlike `Angle`, where one cannot show it any more), perhaps we can live with not fixing it on our side.

**Comment by astrofrog** [comment]
@mhvk - so just to make sure I understand, is your suggestion to just merge https://github.com/astropy/astropy/pull/7234 as-is and then just wait for 1.14.2 for the other issues to be fixed?

**Comment by mhvk** [comment]
@astrofrog - I'm mostly wondering about that.  But it does seem sensible to just merge #7234 as it addresses a specific problem, one that is easier and more urgent than the `FITS_rec` one.

**Comment by saimn** [comment]
Should we just fix the test (at least temporarily) ? Currently all builds are failing because of this.

**Comment by mhvk** [comment]
Agreed. skip the test for `not NUMPY_LT_1_14_1`
