### ISSUE TITLE
Astropy 0.2.4 does not compile with cfitsio 3.35

### ISSUE THREAD

**Issue by mboquien** [astropy/astropy#1287]
Hello,

Building astropy fails when using the following options: --enable-legacy --use-system-libraries. It generated the following error:

```
gcc -pthread -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -march=x86-64 -mtune=native -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c astropy/io/fits/src/compressionmodule.c -o build/temp.linux-x86_64-2.7/astropy/io/fits/src/compressionmodule.o
In file included from /usr/include/python2.7/Python.h:8:0,
                 from astropy/io/fits/src/compressionmodule.c:99:
/usr/include/python2.7/pyconfig.h:1173:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/include/math.h:27:0,
                 from astropy/io/fits/src/compressionmodule.c:97:
/usr/include/features.h:231:0: note: this is the location of the previous definition
 #  define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1728:0,
                 from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:15,
                 from astropy/io/fits/src/compressionmodule.c:100:
/usr/lib/python2.7/site-packages/numpy/core/include/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
  ^
astropy/io/fits/src/compressionmodule.c: In function ‘configure_compression’:
astropy/io/fits/src/compressionmodule.c:662:17: error: ‘FITSfile’ has no member named ‘quantize_dither’
             Fptr->quantize_dither = SUBTRACTIVE_DITHER_1;
                 ^
astropy/io/fits/src/compressionmodule.c:664:17: error: ‘FITSfile’ has no member named ‘quantize_dither’
             Fptr->quantize_dither = 0;
                 ^
astropy/io/fits/src/compressionmodule.c:667:13: error: ‘FITSfile’ has no member named ‘quantize_dither’
         Fptr->quantize_dither = 0;
             ^
error: command 'gcc' failed with exit status 1
```

It works fine when using the cfitsio version included directly in astropy. My cfitsio system version is 3.35 (versus 3.30 for the included version). The package compiles fine with cfitsio 3.34. Looking at the changelog of cfitsio I think I have found the origin of the problem:
- globally changed the variable and/or subroutine name "dither_offset" 
   to "dither_seed" and "quantize_dither" to "quantize_method" so
   that the names more accurately reflects their purpose.

Thanks,

Médéric
