### PR TITLE
Fix table sorting for a single Time column

### LINKED ISSUE #10823: Cannot sort table by Time column
### Description

I have a `Table` with a column containing `Time` objects. I want to sort the rows by that column with `Time` objects. I get `AttributeError: 'Time' object has no attribute 'view'` error. Same error using `QTable`.

I found #8068 but in that issue, the sort wasn't done with the `Time` column even though the table contains a `Time` column.

### Expected behavior

Table successfully sorted in-place by ascending `Time` order.

### Actual behavior

Unsuccessful operation with `AttributeError: 'Time' object has no attribute 'view'` error.

### Steps to Reproduce

```python
>>> from astropy.table import Table
>>> from astropy.time import Time
>>> myrows = [('first row', Time('2001-01-01')), ('second row', Time('1980-12-31'))]
>>> tab = Table(rows=myrows, names=('a', 'b'))
>>> tab.sort('a')  # No error
>>> tab.sort('b')  # Traceback below
```
```
.../astropy/table/table.py in sort(self, keys, reverse)
   2960             keys = [keys]
   2961 
-> 2962         indexes = self.argsort(keys)
   2963 
   2964         if reverse:

.../astropy/table/table.py in argsort(self, keys, kind, reverse)
   2892                 data = self.as_array(names=keys)
   2893             else:
-> 2894                 data = self[keys[0]].view(np.ndarray)
   2895         else:
   2896             # No keys provided so sort on all columns.

.../astropy/time/core.py in __getattr__(self, attr)
   1341         else:
   1342             # Should raise AttributeError
-> 1343             return self.__getattribute__(attr)
   1344 
   1345     @override__dir__

AttributeError: 'Time' object has no attribute 'view'
```

### System Details

Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-glibc2.10
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0]
Numpy 1.19.1
astropy 4.2.dev687+g214a599c1
Scipy 1.5.1
Matplotlib 3.3.1

### PR DESCRIPTION
**Pull request by mhvk**
fixes #10823 

Sorting on a single time column worked in 4.0, but is broken in 4.1-rc2. I milestoned 4.1.1, but perhaps it can still make it for 4.1.

### CODE REVIEW

**Review by taldcroft — APPROVED** [review]
LGTM.
