### ISSUE TITLE
Can't compile using gcc 4.4: NAN and INFINITY undeclared

### ISSUE THREAD

**Issue by ilanschnell** [astropy/astropy#3579]
When trying to compile astropy 1.0.1 on Linux using gcc 4.4.7, I get:
```
gcc44 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/anaconda/lib/python2.7/site-packages/numpy/core/include -I/opt/anaconda/include/python2.7 -c astropy/io/ascii/src/tokenizer.c -o build/temp.linux-x86_64-2.7/astropy/io/ascii/src/tokenizer.o
astropy/io/ascii/src/tokenizer.c: In function ‘str_to_double’:
astropy/io/ascii/src/tokenizer.c:700: error: ‘NAN’ undeclared (first use in this function)
astropy/io/ascii/src/tokenizer.c:700: error: (Each undeclared identifier is reported only once
astropy/io/ascii/src/tokenizer.c:700: error: for each function it appears in.)
astropy/io/ascii/src/tokenizer.c:709: error: ‘INFINITY’ undeclared (first use in this function)
error: command 'gcc44' failed with exit status 1
```

**Comment by embray** [comment]
Thanks for the heads up-- this was fixed in 48268ad275cb523d53b411157b68a108b512ce9a but hasn't made it into a release yet.  A workaround is to run gcc with `-std=c99`.

**Comment by embray** [comment]
(cherry-picked to the v1.0.x branch in 5bddefbb7d57b92d546d6c1014a7511a06e08b0f to ensure this fix isn't left out of the next patch release)

**Comment by ilanschnell** [comment]
Thanks, using `-std-c99` is working fine.
