### ISSUE TITLE
astropy 4.3 fails to compile with CFITSIO 4.0.0

### ISSUE THREAD

**Issue by mboquien** [astropy/astropy#11989]
### Description
When using CFITSIO 4.0.0, astropy 4.3 fails to compile.

### Expected behavior
The package compiles successfully.

### Actual behavior
The package fails to compile with the following error message:

```
  creating build/temp.linux-x86_64-3.9/astropy/io/fits/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -I/tmp/pip-build-env-9h2uoku8/overlay/lib/python3.9/site-packages/numpy/core/include -I/usr/include/python3.9 -c ./astropy/io/fits/src/compressionmodule.c -o build/temp.linux-x86_64-3.9/./astropy/io/fits/src/compressionmodule.o
  In file included from ./astropy/io/fits/src/compressionmodule.c:102:
  ./astropy/io/fits/src/compressionmodule.c: In function ‘configure_compression’:
  ./astropy/io/fits/src/compressionmodule.c:739:19: error: ‘FITSfile’ has no member named ‘quantize_dither’; did you mean ‘quantize_method’?
    739 |             Fptr->quantize_dither = SUBTRACTIVE_DITHER_1;
        |                   ^~~~~~~~~~~~~~~
        |                   quantize_method
  ./astropy/io/fits/src/compressionmodule.c:741:19: error: ‘FITSfile’ has no member named ‘quantize_dither’; did you mean ‘quantize_method’?
    741 |             Fptr->quantize_dither = NO_DITHER;
        |                   ^~~~~~~~~~~~~~~
        |                   quantize_method
  ./astropy/io/fits/src/compressionmodule.c:744:15: error: ‘FITSfile’ has no member named ‘quantize_dither’; did you mean ‘quantize_method’?
    744 |         Fptr->quantize_dither = NO_DITHER;
        |               ^~~~~~~~~~~~~~~
        |               quantize_method
  ./astropy/io/fits/src/compressionmodule.c:747:15: error: ‘FITSfile’ has no member named ‘quantize_dither’; did you mean ‘quantize_method’?
    747 |     if (Fptr->quantize_dither != NO_DITHER) {
        |               ^~~~~~~~~~~~~~~
        |               quantize_method
  ./astropy/io/fits/src/compressionmodule.c:748:60: error: ‘FITSfile’ has no member named ‘dither_offset’; did you mean ‘dither_seed’?
    748 |         switch (get_header_int(header, "ZDITHER0", &(Fptr->dither_offset), 0, HDR_NOFLAG)) {
        |                                                            ^~~~~~~~~~~~~
        |                                                            dither_seed
  ./astropy/io/fits/src/compressionmodule.c:753:19: error: ‘FITSfile’ has no member named ‘dither_offset’; did you mean ‘dither_seed’?
    753 |             Fptr->dither_offset = 0;
        |                   ^~~~~~~~~~~~~
        |                   dither_seed
  ./astropy/io/fits/src/compressionmodule.c:754:19: error: ‘FITSfile’ has no member named ‘request_dither_offset’; did you mean ‘request_dither_seed’?
    754 |             Fptr->request_dither_offset = 0;
        |                   ^~~~~~~~~~~~~~~~~~~~~
        |                   request_dither_seed
  ./astropy/io/fits/src/compressionmodule.c: In function ‘compression_compress_hdu’:
  ./astropy/io/fits/src/compressionmodule.c:1073:16: warning: comparison of integer expressions of different signedness: ‘npy_intp’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
   1073 |     if (znaxis < outbufsize) {
        |                ^
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for astropy
```

### Steps to Reproduce

1. Install CFITSIO 4.0.0.
2. Build a wheel with the ASTROPY_USE_SYSTEM_CFITSIO environment variable set to 1.
3. Observe the aforementioned error message.

Reverting the system CFITSIO to 3.49 immediately fixes the issue. As the maintainer of the Archlinux astropy package I have changed it to use the bundled CFITSIO, but it is not desirable on the long term as it duplicates the system CFITSIO package.

### System Details

Linux-5.13.5-arch1-1-x86_64-with-glibc2.33
Python 3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0]
Numpy 1.20.3
astropy 4.3
Scipy 1.7.0
Matplotlib 3.4.2

**Comment by pllim** [comment]
We have not looked into the new CFITSIO release yet. See #11965

**Comment by saimn** [comment]
Our code did not foresee that there would be a version 4 some day, lol:
https://github.com/astropy/astropy/blob/a8a4b58c10d95abcf19ab642fc25effede7efec4/astropy/io/fits/src/compressionmodule.h#L21-L29

Cfitsio 3.35 was released in 2013 so I guess we could use that as a minimum version instead of maintaining compatibility with older versions.

**Comment by saimn** [comment]
Yes that what I plan (or did locally actually), upgrade the bundle version to 4.0 and require 3.35 as minimal version for external lib. But there is another change with 4.0 that I need to look into, the bundled zlib was removed.
