### ISSUE TITLE
Astropy does not build on MacOSX with Xcode 12.0.0

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#10770]
### Description

When I try to build astropy on my Mac (Catalina + Xcode 12.0) it fails with the following error:

```
  cextern/cfitsio/lib/group.c:5664:8: error: implicit declaration of function 'getcwd' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (!getcwd(buff,FLEN_FILENAME))
         ^
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1

(astropy) ➜  astropy-tmp git:(master) gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Xcode 12.0 was just released Sep. 16 and I'm guessing that it was automatically updated on my Mac since I did not request an update. Astropy is apparently not alone, e.g. https://gitlab.com/graphviz/graphviz/-/issues/1826.

There is a long slack thread with helpful inputs from @saimn, @dhomeier and @manodeep here: https://astropy.slack.com/archives/C067V74GK/p1600984862007700

A workaround is:
```
CFLAGS=-Wno-error=implicit-function-declaration pip install -e .
```

### Expected behavior

Astropy builds and runs tests.

### Actual behavior

Build failed as shown.

### Steps to Reproduce

1. Checkout astropy at master, `git clean -fxd`
2. `tox -e test` or `pip install -e .`

### System Details

```
Darwin-19.5.0-x86_64-i386-64bit
Python 3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.1
astropy 4.2.dev715+gfaccb8b41
Scipy 1.4.1
Matplotlib 3.1.3
```

**Comment by pllim** [comment]
Looks like `export CFLAGS=-DHAVE_UNISTD_H && pip install -e .` also worked for you. So, I guess we pick one of the solutions and go with it?

**Comment by saimn** [comment]
For reference the issue is this new "feature" from Xcode 12:

> Clang now reports an error when you use a function without an explicit declaration when building C or Objective-C code for macOS (-Werror=implicit-function-declaration flag is on). This additional error detection unifies Clang’s behavior for iOS/tvOS and macOS 64-bit targets for this diagnostic. (49917738)

https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes

So we will need a permanent fix for this. We can shut off this warning with `-Wno-error=implicit-function-declaration`, but I was thinking about really fixing the warning by defining `HAVE_UNISTD_H` in cfitsio's compiler options.

**Comment by pllim** [comment]
Re: cfitsio's compiler options -- Does this require upstream fix as well? If so, maybe cfitsio devs need to be informed.

**Comment by dhomeier** [comment]
> Re: cfitsio's compiler options -- Does this require upstream fix as well? If so, maybe cfitsio devs need to be informed.

Is there a Python build maintained upstream? As I commented on Slack, a standard
`./configure; make`
build adds a whole bunch of additional defines for me, compiling on Max OS X 10.12, Xcode 9, without any errors or warnings.
Correctly reproducing the Makefile `DEFS` with `setup.py` for all systems and setups would probably be a more serious task, but for the present issue I'd still vote for adding `CFLAGS=-DHAVE_UNISTD_H` to all Mac builds, since this option compiles with the correct headers and avoids the warnings rather than just making them non-fatal.

**Comment by manodeep** [comment]
Either option should work fine. If the `-Wno-error=implicit-function-declaration` fix actually silences a "real" warning, then the build should break during linking. 

@pllim I imagine that the normal install route for cfitsio users would be through the `configure->make->make install` - in which, this bug should not occur for the regular cfitsio distribution since `-DHAVE_UNISTD_H` is defined by `configure` as @dhomeier pointed out. But no harm in letting the cfitsio devs know anyway right? Particularly, if they either already have a python build or are planning/working on one.
