### ISSUE TITLE
BUG: wcsapi_test.c cannot find wcsconfig.h in exotic archs

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#20045]
Example log: https://github.com/astropy/astropy/actions/runs/28957163984/job/85919083339

7 errors

```
In file included from wcsapi_test.c:10:
  .../astropy/wcs/include/astropy_wcs/astropy_wcs_api.h:4:10: fatal error: wcsconfig.h:
  No such file or directory
      4 | #include "wcsconfig.h"
        |          ^~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/s390x-linux-gnu-gcc' failed with exit code 1
```

Caused by https://github.com/astropy/astropy/pull/19971

**Comment by astrofrog** [comment]
I'll investigate - I suspect this is actually not to do with exotic archs and more to do with when we use a system install of WCSLIB

**Comment by pllim** [comment]
> system install of WCSLIB

Oh, I thought we got rid of that... but maybe I am confusing it with CFITSIO. 🤪
