### ISSUE TITLE
Issue with fit_wcs_from_points when proj_point is passed as a SkyCoord object

### ISSUE THREAD

**Issue by chioettop** [astropy/astropy#10991]
### Description

When calling fit_wcs_from_points() with proj_point=<SkyCoord> object, the following exception is raised:  
```AttributeError: 'str' object has no attribute '_extra_frameattr_names'```

This used to work in Astropy 4.0.

Traceback (most recent call last):
  File "wcs_from_points_bug.py", line 25, in <module>
    projection='TAN'
  File "C:\Users\chioettop\Miniconda3\envs\test1\lib\site-packages\astropy\wcs\utils.py", line 1026, in fit_wcs_from_points
    if (proj_point != 'center') and (type(proj_point) != type(world_coords)):
  File "C:\Users\chioettop\Miniconda3\envs\test1\lib\site-packages\astropy\coordinates\sky_coordinate.py", line 379, in __ne__
    return np.logical_not(self == value)
  File "C:\Users\chioettop\Miniconda3\envs\test1\lib\site-packages\astropy\coordinates\sky_coordinate.py", line 368, in __eq__
    for attr in self._extra_frameattr_names | value._extra_frameattr_names:
AttributeError: 'str' object has no attribute '_extra_frameattr_names'

### Expected behavior

A wcs object should be returned.

### Actual behavior

Traceback (most recent call last):
  File "wcs_from_points_bug.py", line 25, in <module>
    projection='TAN'
  File "C:\Users\chioettop\Miniconda3\envs\test1\lib\site-packages\astropy\wcs\utils.py", line 1026, in fit_wcs_from_points
    if (proj_point != 'center') and (type(proj_point) != type(world_coords)):
  File "C:\Users\chioettop\Miniconda3\envs\test1\lib\site-packages\astropy\coordinates\sky_coordinate.py", line 379, in __ne__
    return np.logical_not(self == value)
  File "C:\Users\chioettop\Miniconda3\envs\test1\lib\site-packages\astropy\coordinates\sky_coordinate.py", line 368, in __eq__
    for attr in self._extra_frameattr_names | value._extra_frameattr_names:
AttributeError: 'str' object has no attribute '_extra_frameattr_names'

### Steps to Reproduce

This script reproduces the error:

```python
import numpy as np
from astropy.wcs.utils import fit_wcs_from_points
from astropy.coordinates import SkyCoord

xy = np.array([[1766.88276168,  662.96432257,  171.50212526,  120.70924648],
               [1706.69832901, 1788.85480559, 1216.98949653, 1307.41843381]])

world_coords = SkyCoord([(66.3542367 , 22.20000162), (67.15416174, 19.18042906),
                         (65.73375432, 17.54251555), (66.02400512, 17.44413253)],
                        frame="icrs", unit="deg")

proj_point = SkyCoord(64.67514918, 19.63389538,
                      frame="icrs", unit="deg")

fit_wcs_from_points(
    xy=xy,
    world_coords=world_coords,
    proj_point=proj_point,
    projection='TAN'
)
```

### System Details

>>> import platform; print(platform.platform())
Windows-10-10.0.19041-SP0
>>> import sys; print("Python", sys.version)
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.19.2
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.3.dev82+gfeee7e5ab
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.5.2

**Comment by pllim** [comment]
cc @cshanahan1 and @ceb8
