### PR TITLE
TST: rank removed in Numpy 1.18

### PR DESCRIPTION
**Pull request by pllim**
Attempt to fix this failure in numpy dev job caused by numpy/numpy#14039
```
AttributeError: module 'numpy' has no attribute 'rank'
```

Example log: https://travis-ci.org/astropy/astropy/jobs/566097785

Note for reviewer: Numpy dev job will still fail due to #8976. I am also not sure what to milestone for Numpy 1.18 support.

### CODE REVIEW

**Comment by bsipocz** [comment]
We still have a numpy dev build for on both release branches. So even  though I said before that it makes no sense to backport this as the numpy 1.18 release will be after we already release the next LTS, our life might be easier if we just backport.
Alternatively the dev testing jobs could probably be removed from those branches.

@mhvk - what do you think?

**Comment by mhvk** [comment]
I think that since numpy >=1.17 is for python3 only, and the python2 compatibility stuff is really meant to be removed for 1.18 (IIRC), it makes little sense to test numpy-dev with LTS. I cannot really imagine why anyone would run astropy 2.0 with numpy >=1.17...

File: astropy/units/tests/test_quantity_non_ufuncs.py [hunk 1]
```diff
@@ -1756,8 +1757,10 @@ def test_is_busday(self):
 untested_functions |= financial_functions
 
 deprecated_functions = {
-    np.asscalar, np.rank
+    np.asscalar
     }
+if NUMPY_LT_1_18:
```
Comment (pllim) [inline astropy/units/tests/test_quantity_non_ufuncs.py]: @mhvk , like this?

**Comment by pllim** [comment]
Just a note that numpy dev will still fail but now it should fail with the 3 tests related to #8976 and not `np.rank`.

https://travis-ci.org/astropy/astropy/jobs/567131469

File: astropy/units/tests/test_quantity_non_ufuncs.py (hunk 1 above)
Comment (bsipocz) [reply astropy/units/tests/test_quantity_non_ufuncs.py]: I think yes, given he said to do the same for the test. With this assumption I go ahead and merge this.

**Comment by bsipocz** [comment]
Thanks @pllim!
