### ISSUE TITLE
TST: 191 failures with numpy-dev

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13464]
Failures are in `coordinates`, `io.ascii`, `table`, and `utils.iers`. Error is `AttributeError: 'MaskedArray' object has no attribute 'info'`

Example log from weekly cron: https://github.com/astropy/astropy/runs/7383859498?check_suite_focus=true

I also restarted a previously passing dev job in `main` and it fails now: https://github.com/astropy/astropy/runs/7390810435?check_suite_focus=true

@seberg thinks it is caused by https://github.com/numpy/numpy/pull/21977 (see https://github.com/numpy/numpy/pull/21999#issuecomment-1187672181)

@mhvk , hope you can advise!

**Comment by mhvk** [comment]
Quite a number of the failures will need an upstream fix. I do not think this will get rid of everything but from the quick look I had, it should not be difficult to ensure we can work with an updated change.

**Comment by pllim** [comment]
We can easily prove it by opening a PR to grab numpy dev from the upstream fix branch. Shall we? 😸

**Comment by mhvk** [comment]
Sounds like the plan is to revert, in which case this can come later.  Which is good, since I don't really have much time right now...

**Comment by pllim** [comment]
I don't see these errors anymore. Thanks again for the quick response!
