### ISSUE TITLE
building io.fits fails due to import_array

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#549]
When I build astropy in python 3.2.3 with numpy 1.6.1 (both from macports) on Mac OS X 10.8, I get the error I've shown below when I do `python setup.py build`. I do _not_ get this error if I build with 2.7.3, though.

Note that if replace `import_array` where the error is generated (`astropy/io/fits/src/compressionmodule.c:979`), it compiles happily and all the tests pass.  I'm not sure if that's a good solution, but it might useful information.

cc: @iguananaut 

```
/usr/bin/clang -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -O2 -I/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/numpy/core/include -Icextern/cfitsio -I/opt/local/Library/Frameworks/Python.framework/Versions/3.2/include/python3.2m -c astropy/io/fits/src/compressionmodule.c -o build/temp.macosx-10.8-x86_64-3.2/astropy/io/fits/src/compressionmodule.o -Wno-unused-variable -Wno-parentheses -Wno-uninitialized -Wno-format -Wno-strict-prototypes -Wno-unused -Wno-comments -Wno-switch
astropy/io/fits/src/compressionmodule.c:979:5: error: void function 'compression_module_init' should not return a value [-Wreturn-type]
    import_array();
    ^~~~~~~~~~~~~~
/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/numpy/core/include/numpy/__multiarray_api.h:1616:144: note: expanded from macro
      'import_array'
#define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return ...
                                                                                                                                               ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
```
