### PR TITLE
Take into account removal of _ones_like ufunc in numpy 1.19.

### LINKED ISSUE #9944: The return of: AttributeError numpy.core.umath has no attribute _ones_like
From a [recent Travis build](https://travis-ci.org/astropy/astropy/jobs/649486180) with numpy-dev:

```
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/pytest_astropy_header/display.py", line 24, in <module>
    from astropy.tests.helper import ignore_warnings
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/tests/helper.py", line 24, in <module>
    from astropy.units import allclose as quantity_allclose  # noqa
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/__init__.py", line 17, in <module>
    from .quantity import *
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/quantity.py", line 29, in <module>
    from .quantity_helper import (converters_and_unit, can_have_arbitrary_unit,
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/quantity_helper/__init__.py", line 10, in <module>
    from . import helpers, function_helpers
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/quantity_helper/helpers.py", line 394, in <module>
    UFUNC_HELPERS[np.core.umath._ones_like] = helper__ones_like
AttributeError: module 'numpy.core.umath' has no attribute '_ones_like'
```

This was previously reported in #7791, and was resolved, but regressed due to a recent cleanup effort in https://github.com/numpy/numpy/pull/15465.

### PR DESCRIPTION
**Pull request by mhvk**
fixes #9944

Note: need to check `numpy-dev` job in particular!

### CODE REVIEW

**Comment by pllim** [comment]
There is a related failure in [numpy-dev job](https://travis-ci.org/astropy/astropy/jobs/649993994). The other one is unrelated, nor the `html-doc`.

**Comment by mhvk** [comment]
That's most bizarre. Looks like `_ones_like` didn't disappear after all!?

**Comment by mhvk** [comment]
Closing since `_ones_like` was in fact not removed (or, rather, its removal from an import statement reverted).
