### PR TITLE
Update cfitsio to 4.0.0

### LINKED ISSUE #11965: ANN: New CFITSIO 4.0.0 released
New CFITSIO release found.

Version: 4.0.0
SONAME: 9

#### Change log

Version 4.0.0 - May 2021                   

  - Removed separate directory for zlib/gzip code, and updated
    configuration to check for zlib on the user's system (required).
    When use of cURL is enabled, it may also pull in zlib such
    that user applications may not need to link with it separately.

  - Changed version numbering to 3-field format.
      
  - Added new calculator functions SETNULL(x,y) to allow substitution of
    NULL values into tables, and GTIOVERLAP() for calculating the amount
    of GTI overlap exposure for a time bin.
    
  - Fix added for proper handling of string columns with zero repeat
    count.
    
  - Fix to column filtering expressions which write #NULL values to
    columns of type (J) format.
    
  - Fix to memory clearing when using polygon shapes in region files.
     
  - Fix to fits_str2time function so that it now flags a particular case
    of bad syntax which was previously getting through.
    
  - In ffgclb and ffpclb (read/write byte columns), the "undocumented"
    feature of being able to transfer columns 'A' string columnss as
    byte arrays is now handled correctly, with improved error checking
    via updates to ffgcprll.  More documentation on string handling is
    in cfitsio.tex.

  - Fix bug in 'colfilter' functionality.  When performing a
    column deletion of the form -COLNAM*, and multiple matches
    existed, then none of the matches got deleted.  Now the
    first is deleted as expected.
    
  - Improved handling of corner case in ffpkn functions.

  - In ffgky, modified TULONG case to allow it to read unsigned
    values greater than the 8-byte signed limit.
    
  - Fix to parsing of corner case of extended file syntax.

  - Major updates to CMake configuration.
		   

(For complete change log information, see https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt .)

### LINKED ISSUE #11989: astropy 4.3 fails to compile with CFITSIO 4.0.0
### Description
When using CFITSIO 4.0.0, astropy 4.3 fails to compile.

### Expected behavior
The package compiles successfully.

### Actual behavior
The package fails to compile with the following error message:

```
  creating build/temp.linux-x86_64-3.9/astropy/io/fits/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -I/tmp/pip-build-env-9h2uoku8/overlay/lib/python3.9/site-packages/numpy/core/include -I/usr/include/python3.9 -c ./astropy/io/fits/src/compressionmodule.c -o build/temp.linux-x86_64-3.9/./astropy/io/fits/src/compressionmodule.o
  In file included from ./astropy/io/fits/src/compressionmodule.c:102:
  ./astropy/io/fits/src/compressionmodule.c: In function ‘configure_compression’:
  ./astropy/io/fits/src/compressionmodule.c:739:19: error: ‘FITSfile’ has no member named ‘quantize_dither’; did you mean ‘quantize_method’?
    739 |             Fptr->quantize_dither = SUBTRACTIVE_DITHER_1;
        |                   ^~~~~~~~~~~~~~~
        |                   quantize_method
  ./astropy/io/fits/src/compressionmodule.c:741:19: error: ‘FITSfile’ has no member named ‘quantize_dither’; did you mean ‘quantize_method’?
    741 |             Fptr->quantize_dither = NO_DITHER;
        |                   ^~~~~~~~~~~~~~~
        |                   quantize_method
  ./astropy/io/fits/src/compressionmodule.c:744:15: error: ‘FITSfile’ has no member named ‘quantize_dither’; did you mean ‘quantize_method’?
    744 |         Fptr->quantize_dither = NO_DITHER;
        |               ^~~~~~~~~~~~~~~
        |               quantize_method
  ./astropy/io/fits/src/compressionmodule.c:747:15: error: ‘FITSfile’ has no member named ‘quantize_dither’; did you mean ‘quantize_method’?
    747 |     if (Fptr->quantize_dither != NO_DITHER) {
        |               ^~~~~~~~~~~~~~~
        |               quantize_method
  ./astropy/io/fits/src/compressionmodule.c:748:60: error: ‘FITSfile’ has no member named ‘dither_offset’; did you mean ‘dither_seed’?
    748 |         switch (get_header_int(header, "ZDITHER0", &(Fptr->dither_offset), 0, HDR_NOFLAG)) {
        |                                                            ^~~~~~~~~~~~~
        |                                                            dither_seed
  ./astropy/io/fits/src/compressionmodule.c:753:19: error: ‘FITSfile’ has no member named ‘dither_offset’; did you mean ‘dither_seed’?
    753 |             Fptr->dither_offset = 0;
        |                   ^~~~~~~~~~~~~
        |                   dither_seed
  ./astropy/io/fits/src/compressionmodule.c:754:19: error: ‘FITSfile’ has no member named ‘request_dither_offset’; did you mean ‘request_dither_seed’?
    754 |             Fptr->request_dither_offset = 0;
        |                   ^~~~~~~~~~~~~~~~~~~~~
        |                   request_dither_seed
  ./astropy/io/fits/src/compressionmodule.c: In function ‘compression_compress_hdu’:
  ./astropy/io/fits/src/compressionmodule.c:1073:16: warning: comparison of integer expressions of different signedness: ‘npy_intp’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
   1073 |     if (znaxis < outbufsize) {
        |                ^
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for astropy
```

### Steps to Reproduce

1. Install CFITSIO 4.0.0.
2. Build a wheel with the ASTROPY_USE_SYSTEM_CFITSIO environment variable set to 1.
3. Observe the aforementioned error message.

Reverting the system CFITSIO to 3.49 immediately fixes the issue. As the maintainer of the Archlinux astropy package I have changed it to use the bundled CFITSIO, but it is not desirable on the long term as it duplicates the system CFITSIO package.

### System Details

Linux-5.13.5-arch1-1-x86_64-with-glibc2.33
Python 3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0]
Numpy 1.20.3
astropy 4.3
Scipy 1.7.0
Matplotlib 3.4.2

### PR DESCRIPTION
**Pull request by saimn**
Closes  #11989, closes #11965.

zlib will be required to compile the extension, will see if I need to add it for the Actions jobs.
Not sure about milestone, previous update was in 4.0.2, maybe we could backport to 4.3.x ?

### Description

This pull request is to address ...

Fixes #<Issue Number>

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label.
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! 🙏 

Hmm... Failed in some jobs.

File: docs/changes/12006.bugfix.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Updated the bundled CFITSIO library to 4.0.0. When compiling with an external
```
Comment (pllim) [inline docs/changes/12006.bugfix.rst:1]: Is this technically a bug? 🤔

**Comment by saimn** [comment]
> Hmm... Failed in some jobs.

Yeah, I have no idea how to install zlib on windows :crying_cat_face: 
Another option is with continue to bundle zlib as it was done with the older versions of cfitsio. Latest version of zlib is from 2017, pretty stable. I think I will go this way unless someone comes with a better solution.

File: docs/changes/12006.bugfix.rst (hunk 1 above)
Comment (saimn) [reply docs/changes/12006.bugfix.rst:1]: Not really but we have been doing that in the past I think. It would be useful for packagers to be able to package astropy 4.3 with cfitsio 4.0

Comment (pllim) [reply docs/changes/12006.bugfix.rst:1]: Sure, but should it be under "others" section instead of "bug fix"?

**Comment by pllim** [comment]
Re: building zlib -- I think that is an acceptable solution. Thanks!

**Comment by mhvk** [comment]
Would it be possible to just follow the `cfitsio` instructions for windows? https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/README.win (sorry, very much a drive-by comment...)

File: docs/changes/12006.bugfix.rst (hunk 1 above)
Comment (saimn) [reply docs/changes/12006.bugfix.rst:1]: Oups, I meant to write "other", I guess we really need the pre-commit check ;)

**Comment by saimn** [comment]
@mhvk - Indeed, installing from source could be an option, but then we would to specific zlib's path when building cfitsio etc.
Also it would be a pain for people installing the dev version of Windows. So bundling zlib with cfistio as we did until now seems the best solution in all aspects.

**Comment by mhvk** [comment]
OK, makes sense, especially since we already (effectively) bundled zlib anyway.

**Comment by pllim** [comment]
What about the CircleCI failures?

**Comment by saimn** [comment]
It's matplotlib so I thought it was unrelated :grimacing: but it's indeed failing to build with cfitsio, and seems to be using an older version of cfitsio which I don't understand... I will investigate later!

File: docs/changes/12006.bugfix.rst (hunk 1 above)
Comment (dhomeier) [reply docs/changes/12006.bugfix.rst]: If people start updating their system cfitsio independently of astropy, it might become a bug...

**Comment by dhomeier** [comment]
> It's matplotlib so I thought it was unrelated 😬 but it's indeed failing to build with cfitsio, and seems to be using an older version of cfitsio which I don't understand... I will investigate later!

It seems to be not even using the sources from this PR
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_UNISTD_H -I/tmp/pip-build-env-g9p9isan/overlay/lib/python3.7/site-packages/numpy/core/include -Icextern/cfitsio/lib -Icextern/cfitsio/zlib -I/root/project/.tox/py37-test-image-mpldev/include -I/usr/local/include/python3.7m -c ./astropy/io/fits/src/compressionmodule.c -o build/temp.linux-x86_64-3.7/./astropy/io/fits/src/compressionmodule.o -Wno-declaration-after-statement -Wno-strict-prototypes -Wno-unused -Wno-uninitialized -Wno-unused-result -Wno-misleading-indentation -Wno-format-overflow
  ./astropy/io/fits/src/compressionmodule.c: In function ‘configure_compression’:
  ./astropy/io/fits/src/compressionmodule.c:709:25: error: ‘CFITSIO_LOSSLESS_COMP_SUPPORTED_VERS’ undeclared (first use in this function)
           if ((version >= CFITSIO_LOSSLESS_COMP_SUPPORTED_VERS) &&

– how can it fail on a line that's been just removed? Triggered a re-run, but still the same.

**Comment by saimn** [comment]
Yes it's compiling lines that have been removed in this PR ... so maybe there is a cache issue or something really weird going on with CircleCI.

**Comment by pllim** [comment]
CircleCI keeps messing up my tox port too. It is trying to pull numpy that isn't there. Drives me crazy! Not sure how to fix it.
