### PR TITLE
WHL: build and distribute stable-ABI-compliant wheels

### LINKED ISSUE #18163: Using the limited Python API in astropy
When building a Python package with C extensions, it is possible to build it against only the limited Python C API (more details at https://docs.python.org/3/c-api/stable.html), which is an API that does not change across minor versions of Python. This makes it possible to build a wheel on e.g. 3.11 and have it also work on 3.12 and 3.13. As an example, Sunpy uses this, and they only have to provide a few wheels, one per platform/architecture:

https://pypi.org/project/sunpy/6.1.1/

Extension-helpers will soon include a change that makes it possible to easily opt in to using this by just adding a single configuration item in ``pyproject.toml``, namely:

```
[tool.distutils.bdist_wheel]
py-limited-api = "cp311"
```

This also requires using Cython 3.1.

Currently this does not work out of the box for astropy core, and there are a few errors we need to resolve:

**column_mixins.pyx**

It looks like Cython support may not be complete here, we should try and see if we can make a minimal example of the failure here and report it upstream.

```
x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPy_LIMITED_API=0x030B0000 -DNPY_TARGET_VERSION=NPY_1_23_API_VERSION -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/home/tom/python/dev/lib/python3.11/site-packages/numpy/_core/include -I/home/tom/python/dev/include -I/usr/include/python3.11 -c astropy/table/_column_mixins.c -o build/temp.linux-x86_64-cpython-311/astropy/table/_column_mixins.o
astropy/table/_column_mixins.c: In function ‘__pyx_f_7astropy_5table_14_column_mixins_column_getitem’:
astropy/table/_column_mixins.c:5217:80: error: invalid use of incomplete typedef ‘PyTypeObject’ {aka ‘struct _typeobject’}
 5217 |   __pyx_t_1 = ((PyTypeObject *)__pyx_mstate_global->__pyx_ptype_5numpy_ndarray)->tp_as_mapping->mp_subscript(__pyx_v_self, __pyx_v_item); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 74, __pyx_L1_error)
      |                                                                                ^~
error: command '/usr/lib/ccache/x86_64-linux-gnu-gcc' failed with exit code 1
```

**storage size unknown**

There are several similar errors:

```
astropy/utils/xml/src/iterparse.c: At top level:
astropy/utils/xml/src/iterparse.c:1105:21: error: storage size of ‘IterParserType’ isn’t known
 1105 | static PyTypeObject IterParserType =
      |                     ^~~~~~~~~~~~~~
error: command '/usr/lib/ccache/x86_64-linux-gnu-gcc' failed with exit code 1
```

```
astropy/wcs/src/astropy_wcs.c:753:21: error: storage size of ‘WcsType’ isn’t known
  753 | static PyTypeObject WcsType = {
      |                     ^~~~~~~
astropy/wcs/src/astropy_wcs.c:753:21: error: storage size of ‘WcsType’ isn’t known
error: command '/usr/lib/ccache/x86_64-linux-gnu-gcc' failed with exit code 1
```

```
astropy/cosmology/_src/signature_deprecations.c: At top level:
astropy/cosmology/_src/signature_deprecations.c:200:21: error: storage size of ‘DeprKwsWrap’ isn’t known
  200 | static PyTypeObject DeprKwsWrap = {
      |                     ^~~~~~~~~~~
cc1: all warnings being treated as errors
error: command '/usr/lib/ccache/x86_64-linux-gnu-gcc' failed with exit code 1
```

Aside from these issues, everything builds fine, so it's not completely impossible to get there!

Need to investigate further what this is due to (similar to astropy.utils error above)

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Close #18163
Close #18336

- [ ] By checking this box, the PR author has requested that maintainers do **NOT** use the "Squash and Merge" button. Maintainers should respect this when possible; however, the final decision is at the discretion of the maintainer that merges the PR.

### CODE REVIEW

**Comment by pllim** [comment]
Do we still need `313t` spec if there is `314` now?

https://github.com/astropy/astropy/blob/91fc8bc8c18c8d4912322ff51d7afdf9bcfef513/.github/workflows/ci_cron_weekly.yml#L71

**Comment by neutrinoceros** [comment]
Yes. The current stable abi doesn't work on 3.13t or 3.14t (which is one of the reasons why we wanted to make it optional), and we can't yet move this job to 3.14t because none of our deps have wheels on PyPI yet.
*but* while we're discussing this, it's worth mentionning that CPython devs *want* the *next* stable abi to be free-threading compatible, so, assuming we can comply with it, we could get 3.15t-instalable wheels for free when we add support for 3.15

**Comment by pllim** [comment]
I don't think change log is needed but release manager can always overrule.

Thanks!

**Comment by neutrinoceros** [comment]
Surprisingly, this works as I expect on macOS and windows (all archs), but not on Linux: all jobs produced 3 wheels each (one for each Python version), never tagging the ABI as `abi3`. Before investigating further, let me ask @astrofrog if he thinks this could be a simple bug in `extensions-helper` ?

**Comment by neutrinoceros** [comment]
never mind I just remembered I saw something similar once; I think it has to do with os-specific ways envs are isolated, and can easily be worked-around in cibuildwheel (once you know what to look for). Let me give this another shot.

**Comment by neutrinoceros** [comment]
Now the env var is correctly passed to the build env on all platforms, however, building currently fails on Linux. It looks to me like the env var isn't having *all* desired effects, in particular, it seems like the  `Py_LIMITED_API` macro is somehow defined too late (i.e., after `Python.h` was already included). I don't yet understand why this problem wasn't caught in existing CI and what's the important difference in a `cibuildwheel` context.
However, it *might* be obvious to @henryiii, so let me try my luck :)

**Comment by neutrinoceros** [comment]
Actually I may have been misreading the logs, I think they were showing genuine compile-time issues (that do not necessarily show up as fatal errors on all compilers, hence why we didn't see them before ?). Any way, I'll try something new and take the compilers seriously for now.

**Comment by neutrinoceros** [comment]
I'm getting there. Letting CI run 100% one last (🤞🏻) time.

**Comment by neutrinoceros** [comment]
Alright, this is now ready for review.

**Review by astrofrog — APPROVED** [review]
Looks good to me!

**Comment by astrofrog** [comment]
Don't think there's any reason not to merge, might as well start exercise this for the dev wheels. We can easily disable the limited API wheels again if needed.

**Comment by pllim** [comment]
Thank you for your hard work on this!

**Comment by astrofrog** [comment]
Yes thank you for the epic effort on this!

**Comment by astrofrog** [comment]
Just to close the loop on this - it all works fine! See dev wheels here:

https://anaconda.org/astropy/astropy/files?type=pypi&version=7.2.dev288%2Bgd02ffa90d6

The wheel building now takes 1h45 instead of 2h15 roughly, so saves 30 minutes on every wheel build job. The reason it hasn't shaved off more is because we still run the test suite on all versions, but I think that's probably sensible for now.

**Comment by neutrinoceros** [comment]
That's actually the recommendation from [Python's docs](https://docs.python.org/3/c-api/stable.html#limited-api-caveats):

> we recommend testing an extension with all minor Python versions it supports, and preferably to build with the lowest such version.
