### ISSUE TITLE
proper motion is not applied in radial velocity correction

### ISSUE THREAD

**Issue by mzechmeister** [astropy/astropy#12878]
I was quite surprised that in the following the proper motion is not applied:

```python
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation
import astropy.units as u
loc = EarthLocation.of_site('lasilla')
jd = Time([2454194.88740019, 2454194.+180], scale='utc', format='jd')

ra = 269.45207695861876 * u.deg    # Barnard's star
de = 4.693364966576667 * u.deg
pmra = 0 * u.mas/u.yr
pmde = 10362.394 * u.mas/u.yr

sc = SkyCoord(ra=ra, dec=de, pm_ra_cosdec=pmra, pm_dec=pmde, distance=1e99*u.pc, equinox=Time('J2000.0'))
sc
sc.radial_velocity_correction(location=loc, obstime=jd)
```
which outputs
```python
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, pc)
    (269.45207696, 4.69336497, 1.e+99)
 (pm_ra_cosdec, pm_dec) in mas / yr
    (0., 10362.394)>
<Quantity [ 25558.65245304, -25741.37060988] m / s>
```
However, removing proper motion by setting `pmde = 0 * u.mas/u.yr` yields exactly the same radial velocities!
(And similar, when changing to `distance=1e3*u.pc`).

Very unexpected. I have seen #10094. So the bug might be related, in particular since I'm using astropy 4.0.1.post1 (+Python 3.6.9), probably a version prior the bug fix.
Anyway, I also tried [`apply_space_motion`](https://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord.apply_space_motion) before `radial_velocity_correction`
(which required some argument juggling (equinox => obstime, times passed in `apply_space_motion` instead of `radial_velocity_correction`)
```
sc = SkyCoord(ra=ra, dec=de, pm_ra_cosdec=pmra, pm_dec=pmde, distance=1e99*u.pc, obstime=Time('J2000.0'))
sc = sc.apply_space_motion(new_obstime=jd)
sc
sc.radial_velocity_correction(location=loc)
```

```
WARNING: ErfaWarning: ERFA function "starpm" yielded 2 of "binary logical OR of the above warnings" [astropy._erfa.core]
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, pc)
    [(269.45207696, 4.69336497, 10000000.),
     (269.45207696, 4.69336497, 10000000.)]
 (pm_ra, pm_dec, radial_velocity) in (mas / yr, mas / yr, km / s)
    [(0., 0., 0.), (0., 0., 0.)]>
<Quantity [ 25558.65245304, -25741.37060985] m / s>
```
So `de` has not changed, while `pm_de` is even gone. 

For comparison, with `barycorrpy` I get `[ 25553.70159307, -25736.00229041]`. So the difference is +5 and -5 m/s, i.e. 10 m/s peak to peak.

* So, what I'm doing something wrong?
* What would be the right approach to support older versions, if possible?
* Or if a bug, which astropy version is reliable?

I'm could find any example with proper motion in the docs.

**Comment by eerovaher** [comment]
I ran the following in the current main branch of `astropy` (i.e. b49ad06b4de9577648a55d499d914e08baeef2c6)
```python
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation
import astropy.units as u
loc = EarthLocation.of_site('lasilla')
jd = Time([2454194.88740019, 2454194.+180], scale='utc', format='jd')
kwargs = {'ra': 269.45207695861876 * u.deg, 'dec': 4.693364966576667 * u.deg,
          'distance': 1e99 * u.pc, 'pm_ra_cosdec': 0 * u.mas/u.yr,
          'pm_dec': 10362.394 * u.mas/u.yr,
          'obstime': Time('J2000', scale='utc')}
sc = SkyCoord(**kwargs)
sc = sc.apply_space_motion(new_obstime=jd)
sc.radial_velocity_correction(location=loc, obstime=jd)
```
The output is very close to what you reported:
```
ErfaWarning: ERFA function "pmsafe" yielded 2 of "binary logical OR of the above warnings"
<Quantity [ 25558.65291868, -25741.37029469] m / s>
```
When I change the distance to be more realistic
```python
kwargs['distance'] = 1.82*u.pc
sc = SkyCoord(**kwargs)
sc = sc.apply_space_motion(new_obstime=jd)
sc.radial_velocity_correction(location=loc, obstime=jd)
```
then I obtain numbers very close to what you obtained with `barcorrpy`, and there aren't any warnings:
```
<Quantity [ 25553.65807097, -25735.94691141] m / s>
```
But the following code
```python
sc = SkyCoord(**kwargs)
sc.radial_velocity_correction(location=loc, obstime=jd)
```
produces
```
<Quantity [ 25521.06974594, -25770.73201162] m / s>
```
which is quite different from the outputs above, and even more disturbingly the following
```python
sc = SkyCoord(**kwargs)
sc = sc.apply_space_motion(new_obstime=jd)
print(sc)
sc.radial_velocity_correction(location=loc, obstime=jd)
```
results in 
```
AttributeError: 'SphericalCosLatDifferential' object has no attribute 'd_lon'
```
It looks like there is indeed a bug, but I don't have a quick solution.

**Comment by JohnPritchard** [comment]
Hi, has there been any progress on this issue? Or more precisely, the "AttributeError: 'SphericalCosLatDifferential' object has no attribute 'd_lon'" issue lastly identified in the previous comment.
Working with 5.1.1, if I do (as above):
```
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation
import astropy.units as u
loc = EarthLocation.of_site('lasilla')
jd = Time([2454194.88740019, 2454194.+180], scale='utc', format='jd')
kwargs = {'ra': 269.45207695861876 * u.deg, 'dec': 4.693364966576667 * u.deg,
          'distance': 1.82*u.pc, 'pm_ra_cosdec': 0 * u.mas/u.yr,
          'pm_dec': 10362.394 * u.mas/u.yr,
          'obstime': Time('J2000', scale='utc')}
```
And then:
```
sc = SkyCoord(**kwargs)
sc = sc.apply_space_motion(new_obstime=jd)
print(sc)
sc.radial_velocity_correction(location=loc, obstime=jd)
```
The as above I get:
```
AttributeError: 'SphericalCosLatDifferential' object has no attribute 'd_lon'
```
But if I omit the print statement, i.e.:
```
sc = SkyCoord(**kwargs)
sc = sc.apply_space_motion(new_obstime=jd)
sc.radial_velocity_correction(location=loc, obstime=jd)
```
I get:
```
<Quantity [ 25553.65807097, -25735.94691141] m / s>
```
(which is very close to the `barycorrpy` result = `[ 25553.70159307, -25736.00229041]`.)
