### PR TITLE
Ensure FITS_rec can be indexed with a tuple even if it returns a scalar.

### PR DESCRIPTION
**Pull request by mhvk**
While investigating numpy-dev failures, I noticed one of them was caused by indexing a `FITS_rec` instance with a tuple of the form `(number,)`, i.e., one that just returns a scalar. This causes a failure (see below) because the `__getitem__` code assumes any tuple key will return a view on the original array (another example of why one should not LBYL but rather EAFP...). This fixes the problem, though scalar lookup will now become somewhat more expensive (probably, a real fix would be to deal with the reference issues that force one to go through the current hoops).

```
import numpy as np
from astropy.io.fits import FITS_rec
x = np.array([(1.0, 2), (3.0, 4)], dtype=[('x', float), ('y', int)]).view(FITS_rec)
x[1,]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-aacf971fccce> in <module>()
      2 from astropy.io.fits import FITS_rec
      3 x = np.array([(1.0, 2), (3.0, 4)], dtype=[('x', float), ('y', int)]).view(FITS_rec)
----> 4 x[1,]

/usr/lib/python3/dist-packages/astropy/io/fits/fitsrec.py in __getitem__(self, key)
    490             subtype = type(self)
    491             out = self.view(np.recarray).__getitem__(key).view(subtype)
--> 492             out._coldefs = ColDefs(self._coldefs)
    493             arrays = []
    494             out._converted = {}

/usr/lib/python3/dist-packages/numpy/core/records.py in __setattr__(self, attr, val)
    265             else:
    266                 raise AttributeError("'record' object has no "
--> 267                         "attribute '%s'" % attr)
    268 
    269     def __getitem__(self, indx):

AttributeError: 'record' object has no attribute '_coldefs'
```

### CODE REVIEW

**Comment by mhvk** [comment]
ps. The reason this leads to failures on `numpy-dev` is that the new `arrayprint` routine indexes the array using tuples. So, we need to fix this to be able to use `numpy-dev` with fits tables, otherwise `repr` will break.

**Comment by bsipocz** [comment]
@mhvk - Is this critical for 2.0.3?

**Comment by mhvk** [comment]
@bsipocz - yes if we want 2.0.3 to work with numpy 1.14. I'm fairly confident the fix is correct, but it would still be good to get some review (@saimn, @MSeifert04, @drdavella?).

**Comment by bsipocz** [comment]
OK, thanks for the confirmation.

**Comment by bsipocz** [comment]
Changes here is not np1.9 compatible for the backport:
https://travis-ci.org/astropy/astropy/jobs/314820655

**Comment by mhvk** [comment]
@bsipocz - one could try `type(out) is not np.recarray` instead of `type(out) is np.record`. Should I restore the branch to try that?

**Comment by bsipocz** [comment]
At this point I think the clearest would be to open a PR against the 2.0.x branch? Or if you are happy to have that change in master, against master and then I'll backport.

**Comment by mhvk** [comment]
See #6966
