### ISSUE TITLE
The return of: AttributeError numpy.core.umath has no attribute _ones_like

### ISSUE THREAD

**Issue by eslavich** [astropy/astropy#9944]
From a [recent Travis build](https://travis-ci.org/astropy/astropy/jobs/649486180) with numpy-dev:

```
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/pytest_astropy_header/display.py", line 24, in <module>
    from astropy.tests.helper import ignore_warnings
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/tests/helper.py", line 24, in <module>
    from astropy.units import allclose as quantity_allclose  # noqa
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/__init__.py", line 17, in <module>
    from .quantity import *
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/quantity.py", line 29, in <module>
    from .quantity_helper import (converters_and_unit, can_have_arbitrary_unit,
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/quantity_helper/__init__.py", line 10, in <module>
    from . import helpers, function_helpers
  File "/home/travis/build/astropy/astropy/.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/quantity_helper/helpers.py", line 394, in <module>
    UFUNC_HELPERS[np.core.umath._ones_like] = helper__ones_like
AttributeError: module 'numpy.core.umath' has no attribute '_ones_like'
```

This was previously reported in #7791, and was resolved, but regressed due to a recent cleanup effort in https://github.com/numpy/numpy/pull/15465.

**Comment by pllim** [comment]
Shouldn't this be reported upstream to Numpy? cc @mhvk

**Comment by mhvk** [comment]
It is a private function included mostly for completeness - I guess it is finally removed by numpy, so we should just skip it if not present.  Will make a PR.

**Comment by mhvk** [comment]
See #9945

**Comment by mhvk** [comment]
Well, we may not have cared but this *was* fixed upstream - see https://github.com/numpy/numpy/pull/15560

I'll close this issue as well as my PR for now - @eslavich - thanks for noticing, even if it went away! And of course do report again if it returns...
