### ISSUE TITLE
TST/BUG: daily cron is failing on newly introduced tests

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#18260]
[example logs](https://github.com/astropy/astropy/actions/runs/15575273698/job/43858850268)
Failing tests were introduced in #18118 
It's not clear to me at the moment what's so special about the broken job that it's failing while regular CI passed.

ping @mhvk

**Comment by pllim** [comment]
```
>       version_mod = getattr(const, version)
                      ^^^^^^^^^^^^^^^^^^^^^^^
E       AttributeError: module 'astropy.constants' has no attribute 'iau2012'
```

Somehow `getattr` not happy in pyinstaller.

I wonder if we tackle that first, the cryptic subprocess error would go away.

**Comment by mhvk** [comment]
Easiest would be to exclude under `pyinstaller`, but better of course to fix it. Though how? I tried `tox -e pyinstaller` and things just pass...

**Comment by pllim** [comment]
@mhvk  did you use Python 3.11? I don't use pyinstaller so this is very mysterious to me as well.

**Comment by pllim** [comment]
@astrofrog any idea?

**Comment by pllim** [comment]
Since no one has better idea, I propose we skip them for now: https://github.com/astropy/astropy/pull/18290
