### PR TITLE
Remove unnecessary scipy imports

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address comment from @dhomeier at https://github.com/astropy/astropy/pull/13654/files#r968968361 . This is a direct follow-up of https://github.com/astropy/astropy/pull/13651 .

Very uncontroversial. If CI passes, I might just YOLO-merge it.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Do the proposed changes actually accomplish desired goals?
- [x] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [x] Do the proposed changes need the code-style [fixed](https://docs.astropy.org/en/latest/development/workflow/maintainer_workflow.html#pre-commit_bot)?
- [x] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [x] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [x] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [x] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [x] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [x] Is this a big PR that makes a "What's new?" entry worthwhile and if so, is (1) a "what's new" entry included in this PR and (2) the "whatsnew-needed" label applied?
- [x] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [x] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Review by Cadair — APPROVED** [review]

**Comment by pllim** [comment]
Restarting the CI to see if the failure is transient.

**Comment by saimn** [comment]
This would work only with scipy > 1.9.0 I think.

**Comment by pllim** [comment]
This just cleans up something else that's already merged, so I am merging this too. If you disagree on the actual fix, please submit a follow-up PR. Thanks!

**Comment by saimn** [comment]
> @saimn , but the oldest deps CI job passed with Scipy: 1.3.3.

That's a bit surprising. Lazy loading was added in scipy 1.9.0:
```
In [1]: import scipy

In [2]: scipy.__version__
Out[2]: '1.8.1'

In [3]: scipy.misc.ascent
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 scipy.misc.ascent

AttributeError: module 'scipy' has no attribute 'misc'
```

**Comment by dhomeier** [comment]
> That's a bit surprising. Lazy loading was added in scipy 1.9.0:
> 
Yes, thought I had tested it, but now confirmed with 1.8.1 it doesn't work on its own.
I guess in the tests `scipy.misc` has already been imported sometime earlier, but to run that test by itself, it's probably safer to keep that first import.

**Comment by pllim** [comment]
Partially reverted on `main` at https://github.com/astropy/astropy/commit/975abba6084402e754a43c92e469d5fdf9d7545c

**Comment by pllim** [comment]
Good catch, @saimn . Thanks!
