### ISSUE TITLE
[6.1.1] FK5.equinox.jyear missing

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#16654]
### Description

I am not sure whether this is a bug in Astropy or in [APLPy](https://github.com/aplpy/aplpy): with Astropy 6.1.1, I get [test failures](https://ci.debian.net/packages/a/aplpy/testing/amd64/48397735/) of APLPy 2.1.0, for example:
```
 _____________________________ test_beam_add_remove _____________________________
    def test_beam_add_remove():
>       f = FITSFigure(HDU)
[…]
>           equinox = "{:g}".format(FK5.equinox.jyear)
E           AttributeError: 'TimeAttribute' object has no attribute 'jyear'
 
/usr/lib/python3/dist-packages/aplpy/axis_labels.py:47: AttributeError
```
This is a regression; the same tests work well with Astropy 6.0.0.

As **FK5** is a class (which I'd expect to have constant attributes), and I didn't find anything about **jyear** or **TimeAttribute** in the Changelog, and also not in a (very quick) review of the changes, I could imagine that is "somehow" a bug in Astropy. FK5 is directly imported on top of [`axis_labels.py`](https://github.com/aplpy/aplpy/blob/00bbe28bea179b120e39818a9f171159b51333e4/aplpy/axis_labels.py).

What makes it more confusing is that one finds a [few tests](https://github.com/astropy/astropy/blob/13d314c53a28759983b40c91e31bf08dbfe378f2/astropy/coordinates/tests/test_arrays.py#L191) that use **fk5.equinox.jyear** (accessed from an **FK5** object, however; not from the **FK5** class), so I am not sure whether this is a bug in Astropy or APLPy wrongly used the class before and this is now uncovered. Please transform the issue to APLPy if this is an issue there.

Cc @astrofrog as APLPy maintainer

### Expected behavior

I'd guess the test  should succeed.

### How to Reproduce

Run the pytest of APLPy

### Versions

* Debian testing
* APLPy 2.1.0
* Astropy 6.1.1
* numpy 1.26.4
* matplotlib 3.6.3

**Comment by mhvk** [comment]
An easier reproducer:
```
In [1]: from astropy.coordinates import FK5

In [2]: FK5.equinox
Out[2]: <astropy.coordinates.attributes.TimeAttribute at 0x7f7ebc037b50>

In [3]: FK5.equinox.jyear
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 FK5.equinox.jyear

AttributeError: 'TimeAttribute' object has no attribute 'jyear'
```
This is almost certainly due to #15259, which changed how an attribute directly retrieved from a class is treated. That said, this seems a totally valid use case, so let me ping @ayshih to see if he has a suggestion on how we can fix this regression while not losing the benefit of having a sensible docstring:
```
# current master
In [2]: FK5.equinox?
Type:            TimeAttribute
String form:     <astropy.coordinates.attributes.TimeAttribute object at 0x7f29e35242d0>
File:            ~/data/mhvk/packages/astropy/astropy/coordinates/attributes.py
Docstring:      
The equinox time

Default: J2000.000
Class docstring:
Frame attribute descriptor for quantities that are Time objects.
See the `~astropy.coordinates.Attribute` API doc for further
information.

# 6.0
Type:        Time
String form: J2000.000
File:        /usr/lib/python3/dist-packages/astropy/time/core.py
Docstring:  
Represent and manipulate times and dates for astronomy.

A `Time` object is initialized with one or more times in the ``val``
argument.  The input times in ``val`` must conform to the specified
``format`` and must correspond to the specified time ``scale``.  The
optional ``val2`` time input should be supplied only for numeric input
formats (e.g. JD) where very high precision (better than 64-bit precision)
is required.
.
.
.
```

p.s. The work-around would be `FK5().equinox.jyear` - though really this is of course fixed to 2000.0 - it defines FK5...

**Comment by pllim** [comment]
That is unfortunate. How did this get past integration testing of RC? 🧐

**Comment by ayshih** [comment]
> The work-around would be `FK5().equinox.jyear`

Depending on your perspective, a clearer workaround might be `FK5.equinox.default.jyear`.  That is, instead of instantiating the class, you just need to explicitly retrieve the default value for the frame attribute when accessed on the frame class.

> let me ping @ayshih to see if he has a suggestion on how we can fix this regression while not losing the benefit of having a sensible docstring

I don't have any bright ideas.  The tricky aspect is that there are two types of frame-attribute defaults.  The default J2000.0 for the `equinox` frame attribute on `FK5` is correct in all but the most unusual circumstances, so it would be nice to spit that out readily.  However, there are frame attributes such as `obstime` on `GCRS` where the default value (also J2000.0) is *incorrect* in all but the most unusual circumstances, and is largely there as a placeholder so that nothing breaks.

**Comment by olebole** [comment]
Couldn't one just remove the class attributes here? APLPy is not a real use case; [the code in question is](https://github.com/aplpy/aplpy/blob/00bbe28bea179b120e39818a9f171159b51333e4/aplpy/axis_labels.py#L45-L49):
```Python
        elif isinstance(frame, FK5):

            equinox = "{:g}".format(FK5.equinox.jyear)
            xtext = 'RA (J{0})'.format(equinox)
            ytext = 'Dec (J{0})'.format(equinox)
```
IMO this is not so correct anyway; wouldn't one better write
```Python
            equinox = "{:g}".format(frame.equinox.jyear)
```
to be correct under all (incl. the unusual) circumstances?

**Comment by ayshih** [comment]
Indeed, for this specific code in APLpy, it's actually bugged for `equinox` of non-default value, so one should make the change you suggest, so this issue is moot.  Same for this line as well:
https://github.com/aplpy/aplpy/blob/00bbe28bea179b120e39818a9f171159b51333e4/aplpy/axis_labels.py#L53

**Comment by pllim** [comment]
Do I understand correctly that this has been now identified as a downstream bug?

**Comment by ayshih** [comment]
In my opinion, yes

**Comment by pllim** [comment]
So @olebole , should we open an issue over at aplpy and close this one? Since it is in a different org, I cannot just move this issue. Thanks!

**Comment by olebole** [comment]
No; please just keep this one open. I will create a PR for APLPy that closes it.

**Comment by astroww** [comment]
`FK5.equinox.default.jyear`  works well for me
