### PR TITLE
Backport PR #12516 on branch v5.0.x (Use +FLOAT_CMP to fix test failure on i386 and others in convolve.py)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #12516: Use +FLOAT_CMP to fix test failure on i386 and others in convolve.py

### CODE REVIEW

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
Hmm, @mhvk , is `E   TypeError: Too few arguments for Quantity` that failed here fixed by #12511 ?

**Comment by mhvk** [comment]
@pllim - yes, that error is fixed by #12511, so this should be safe!

**Comment by pllim** [comment]
Alas, we have fast-fail mode... Maybe we need to merge #12519 first and then figure out how to get the bot to rebase.

**Comment by mhvk** [comment]
Slightly aside: was it a conscious decision to make `numpy-dev` failures no longer "allowed to fail"?

**Comment by pllim** [comment]
> was it a conscious decision 

No. I don't remember changing any settings on that front.

Actually now that I look at the log, why is CI installing numpy-dev for "Python 3.10 with minimal dependencies" ???

**Comment by pllim** [comment]
Hmm, @saimn , do we really want `devdeps` in CI matrix that is not allowed to fail? What was the motivation for this again?

https://github.com/astropy/astropy/blob/aad78c28e17098ade4d821c8b65a34eec8806dbd/.github/workflows/ci_workflows.yml#L67

**Comment by saimn** [comment]
As far as I remember it was requested to put py3.10 on the dev job, since py3.10 was still in rc. (And then there were the asdf-dev failures).

**Comment by pllim** [comment]
I am going to see if I can force a rebase but closing this without merge and then manually triggering the bot from the original PR... 🤞
