### ISSUE TITLE
Astropy 1.0.4 does not compile with wcslib 5.9

### ISSUE THREAD

**Issue by mboquien** [astropy/astropy#4081]
Hello,

The 1.0.4 version of Astropy does not compile with wcslib 5.9 and gcc 5.2.0. The message is the following:

```
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=native -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fPIC -DECHO -DWCSTRIG_MACRO -DASTROPY_WCS_BUILD -D_GNU_SOURCE -DNDEBUG -DHAVE_SINCOS -UDEBUG -I/usr/lib/python3.4/site-packages/numpy/core/include -Iastropy/wcs/include -I/usr/include/wcslib -I/usr/include/python3.4m -c astropy/wcs/src/pipeline.c -o build/temp.linux-x86_64-3.4/astropy/wcs/src/pipeline.o
astropy/wcs/src/pipeline.c: In function ‘pipeline_all_pixel2world’:
astropy/wcs/src/pipeline.c:93:16: warning: implicit declaration of function ‘wcserr_set’ [-Wimplicit-function-declaration]
       status = wcserr_set(
                ^
astropy/wcs/src/pipeline.c:12:28: warning: implicit declaration of function ‘WCSERR_SET’ [-Wimplicit-function-declaration]
 #define PIP_ERRMSG(status) WCSERR_SET(status)
                            ^
astropy/wcs/src/pipeline.c:94:9: note: in expansion of macro ‘PIP_ERRMSG’
         PIP_ERRMSG(WCSERR_BAD_COORD_TRANS),
         ^
astropy/wcs/src/pipeline.c:146:42: error: invalid application of ‘sizeof’ to incomplete type ‘struct wcserr’
         pipeline->err = calloc(1, sizeof(struct wcserr));
                                          ^
astropy/wcs/src/pipeline.c:148:7: warning: implicit declaration of function ‘wcserr_copy’ [-Wimplicit-function-declaration]
       wcserr_copy(pipeline->wcs->err, pipeline->err);
       ^
astropy/wcs/src/pipeline.c:69:19: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
   struct wcserr **err;
                   ^
astropy/wcs/src/pipeline.c:60:22: warning: unused variable ‘function’ [-Wunused-variable]
   static const char* function = "pipeline_all_pixel2world";
                      ^
astropy/wcs/src/pipeline.c: In function ‘pipeline_pix2foc’:
astropy/wcs/src/pipeline.c:235:42: error: invalid application of ‘sizeof’ to incomplete type ‘struct wcserr’
         pipeline->err = calloc(1, sizeof(struct wcserr));
                                          ^
astropy/wcs/src/pipeline.c:181:20: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
   struct wcserr  **err;
                    ^
astropy/wcs/src/pipeline.c:173:22: warning: unused variable ‘function’ [-Wunused-variable]
   static const char* function = "pipeline_pix2foc";
                      ^
error: command 'gcc' failed with exit status 1
```
Thanks!

**Comment by embray** [comment]
I don't believe Astropy 1.0.x supports WCSLIB 5.x.  WCSLIB 5.x will only be supported in v1.1 and up (see #3845 and various related PRs).

**Comment by mdboom** [comment]
Just confirming @embray's response, as the author of the astropy.wcs package.  wcslib 5.x broke compatibility in significant ways that are currently only on astropy master (though will make it into the astropy 1.1 release).
