### PR TITLE
Ensure np.linalg overrides continue to work with numpy >= 1.25

### LINKED ISSUE #14846: numpy-dev (1.25) deprecation for find_common_type and some __new__
23 new failures from numpy-dev with things like this:

```
FAILED astropy/stats/tests/test_funcs.py::test_kuiper_two_uniform[...] - DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
```
```
FAILED astropy/stats/tests/test_funcs.py::test_kuiper_two_nonuniform[...] - DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
```
```
FAILED astropy/stats/tests/test_funcs.py::test_detect_kuiper_two_different - DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
```
```
FAILED astropy/stats/tests/test_funcs.py::test_fpp_kuiper_two[...] - DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
```
```
FAILED astropy/units/tests/test_quantity_non_ufuncs.py::TestLinAlg::test_svd - TypeError: SVDResult.__new__() missing 2 required positional arguments: 'S' and 'Vh'
```
```
FAILED astropy/units/tests/test_quantity_non_ufuncs.py::TestLinAlg::test_qr - TypeError: QRResult.__new__() missing 1 required positional argument: 'R'
```
```
FAILED astropy/units/tests/test_quantity_non_ufuncs.py::TestLinAlg::test_eig
FAILED astropy/units/tests/test_quantity_non_ufuncs.py::TestLinAlg::test_eigh
-  TypeError: EigResult.__new__() missing 1 required positional argument: 'eigenvectors'
```

Example log: https://github.com/astropy/astropy/actions/runs/5018146818/jobs/8997192325?pr=14845

cc @larrybradley and @mhvk

### PR DESCRIPTION
**Pull request by mhvk**
In numpy >=1.25, some functions return namedtuple, which is nice but sadly needs special treatment.

Fixes #14846 (together with #14859)

(Not sure about backporting - did 5.3 only, but perhaps should do 5.0? Then again, #14589 was only backported to 5.3)

### CODE REVIEW

**Review by larrybradley — APPROVED** [review]
Thanks, @mhvk!

**Comment by mhvk** [comment]
@pllim - I think this is ready to go in, as long as it is OK not to backport to 5.0 (I think it would be a clean backport, but we didn't do #14589)

**Comment by eerovaher** [comment]
@mhvk, #14591 was backported to 5.0 as #14595.

**Comment by pllim** [comment]
No need to backport to v5.0.x because we already pin `numpy<1.25` there after the sin/cos "upgrades".

**Comment by pllim** [comment]
Thank you! So nice to see CI all green again.
