### ISSUE TITLE
Compilation failure of wcs/src/wcslib_wrap.c with astropy 0.4.4

### ISSUE THREAD

**Issue by mboquien** [astropy/astropy#3374]
Hello,

Trying to update the Arch Linux package for astropy 0.4.4, I am running into a compilation failure of wcs/src/wcslib_wrap.c with the following output:

```
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DECHO -DWCSTRIG_MACRO -DASTROPY_WCS_BUILD -D_GNU_SOURCE -DWCSVERSION=4.20 -DNDEBUG -DHAVE_SINCOS -UDEBUG -I/usr/lib/python2.7/site-packages/numpy/core/include -Iastropy/wcs/include -I/usr/include/wcslib -I/usr/include/python2.7 -c astropy/wcs/src/wcslib_wrap.c -o build/temp.linux-x86_64-2.7/astropy/wcs/src/wcslib_wrap.o
In file included from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from astropy/wcs/include/astropy_wcs/pyutil.h:15,
                 from astropy/wcs/include/astropy_wcs/wcslib_wrap.h:9,
                 from astropy/wcs/src/wcslib_wrap.c:8:
/usr/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
astropy/wcs/src/wcslib_wrap.c: In function ‘PyWcsprm_compare’:
astropy/wcs/src/wcslib_wrap.c:754:12: error: incompatible type for argument 2 of ‘wcscompare’
   status = wcscompare(cmp, &self->x, &other->x, &equal);
            ^
In file included from astropy/wcs/include/astropy_wcs/util.h:21:0,
                 from astropy/wcs/include/astropy_wcs/pyutil.h:9,
                 from astropy/wcs/include/astropy_wcs/wcslib_wrap.h:9,
                 from astropy/wcs/src/wcslib_wrap.c:8:
/usr/include/wcslib/wcs.h:1576:5: note: expected ‘double’ but argument is of type ‘struct wcsprm *’
 int wcscompare(int cmp, double tol, const struct wcsprm *wcs1,
     ^
astropy/wcs/src/wcslib_wrap.c:754:49: warning: passing argument 4 of ‘wcscompare’ from incompatible pointer type
   status = wcscompare(cmp, &self->x, &other->x, &equal);
                                                 ^
In file included from astropy/wcs/include/astropy_wcs/util.h:21:0,
                 from astropy/wcs/include/astropy_wcs/pyutil.h:9,
                 from astropy/wcs/include/astropy_wcs/wcslib_wrap.h:9,
                 from astropy/wcs/src/wcslib_wrap.c:8:
/usr/include/wcslib/wcs.h:1576:5: note: expected ‘const struct wcsprm *’ but argument is of type ‘int *’
 int wcscompare(int cmp, double tol, const struct wcsprm *wcs1,
     ^
astropy/wcs/src/wcslib_wrap.c:754:12: error: too few arguments to function ‘wcscompare’
   status = wcscompare(cmp, &self->x, &other->x, &equal);
            ^
In file included from astropy/wcs/include/astropy_wcs/util.h:21:0,
                 from astropy/wcs/include/astropy_wcs/pyutil.h:9,
                 from astropy/wcs/include/astropy_wcs/wcslib_wrap.h:9,
                 from astropy/wcs/src/wcslib_wrap.c:8:
/usr/include/wcslib/wcs.h:1576:5: note: declared here
 int wcscompare(int cmp, double tol, const struct wcsprm *wcs1,
     ^
astropy/wcs/src/wcslib_wrap.c: In function ‘PyWcsprm_richcompare’:
astropy/wcs/src/wcslib_wrap.c:1699:14: error: incompatible type for argument 2 of ‘wcscompare’
     status = wcscompare(
              ^
In file included from astropy/wcs/include/astropy_wcs/util.h:21:0,
                 from astropy/wcs/include/astropy_wcs/pyutil.h:9,
                 from astropy/wcs/include/astropy_wcs/wcslib_wrap.h:9,
                 from astropy/wcs/src/wcslib_wrap.c:8:
/usr/include/wcslib/wcs.h:1576:5: note: expected ‘double’ but argument is of type ‘struct wcsprm *’
 int wcscompare(int cmp, double tol, const struct wcsprm *wcs1,
     ^
astropy/wcs/src/wcslib_wrap.c:1701:17: warning: passing argument 4 of ‘wcscompare’ from incompatible pointer type
         ax, bx, &equal);
                 ^
In file included from astropy/wcs/include/astropy_wcs/util.h:21:0,
                 from astropy/wcs/include/astropy_wcs/pyutil.h:9,
                 from astropy/wcs/include/astropy_wcs/wcslib_wrap.h:9,
                 from astropy/wcs/src/wcslib_wrap.c:8:
/usr/include/wcslib/wcs.h:1576:5: note: expected ‘const struct wcsprm *’ but argument is of type ‘int *’
 int wcscompare(int cmp, double tol, const struct wcsprm *wcs1,
     ^
astropy/wcs/src/wcslib_wrap.c:1699:14: error: too few arguments to function ‘wcscompare’
     status = wcscompare(
              ^
In file included from astropy/wcs/include/astropy_wcs/util.h:21:0,
                 from astropy/wcs/include/astropy_wcs/pyutil.h:9,
                 from astropy/wcs/include/astropy_wcs/wcslib_wrap.h:9,
                 from astropy/wcs/src/wcslib_wrap.c:8:
/usr/include/wcslib/wcs.h:1576:5: note: declared here
 int wcscompare(int cmp, double tol, const struct wcsprm *wcs1,
     ^
error: command 'gcc' failed with exit status 1
```

I am building with the following command line: python2 setup.py build --use-system-libraries --offline. Note that I get the exact same issue with Python 3. I am using gcc 4.9.2 and wcslib 4.24. Looking at the changelog of WCSlib, that my be related to a modification that was included in 4.24: "- Changed API to wcscompare() to allow a tolerance to be specified for floating-point comparisons.  Contributed by Michael Droettboom.". It appears that the WCSlib shipped with astropy 0.4.4 is version 4.23, so it predates this change.  I guess @mdboom is the expert here.

Thanks!

Médéric

**Comment by embray** [comment]
I'm going to close this as a duplicate of #2976, but feel free to continue commenting here or in the other issue until your issue is resolved.  Your best bet is to build with the wcslib bundled with Astropy.

**Comment by mdboom** [comment]
Yes.  0.4.4 works with wcslib 4.23 only.  master (and the upcoming 1.0) works with wcslib 4.24 and later.

**Comment by mboquien** [comment]
OK, thanks. I searched the open and closed issues and could not find anything. Will search harder next time.

**Comment by mboquien** [comment]
Is the release of 1.0 imminent or is it worth that I apply a patch to build the package?

**Comment by embray** [comment]
No problem, having more issues should make it easier to find in the future.

1.0 should be out soon but the patch is also simple enough.
