### ISSUE TITLE
AstropyDeprecationWarning 

### ISSUE THREAD

**Issue by CTJChen** [astropy/astropy#12827]
### Description

Normal astropy.io.fits operations that may raise warnings seem to stopped working with IPython 8.0+:

### Expected behavior

With python 3.8.10 and ipython 7.22.0, 
I get a warning for fits formatting issues but not a bug. 
```
In [4]: newdatahdu = fits.BinTableHDU(data=datahdu.data.copy(), header=datahdu.header.copy())
WARNING: AstropyDeprecationWarning: The following keywords are now recognized as special column-related attributes and should be set via the Column objects: TCDLTn, TCRPXn, TCRVLn, TCTYPn, TCUNIn. In future, these values will be dropped from manually specified headers automatically and replaced with values generated based on the Column objects. [astropy.io.fits.hdu.table]
```

##### In [5]: newdatahdu = fits.BinTableHDU(data=data, header=header)
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [5], in <module>
----> 1 newdatahdu = fits.BinTableHDU(data=data, header=header)

File ~/pyenvs/artxc/lib/python3.8/site-packages/astropy/io/fits/hdu/table.py:858, in BinTableHDU.__init__(self, data, header, name, uint, ver, character_as_bytes)
    855     data = hdu.data
    856     header = hdu.header
--> 858 super().__init__(data, header, name=name, uint=uint, ver=ver,
    859                  character_as_bytes=character_as_bytes)

File ~/pyenvs/artxc/lib/python3.8/site-packages/astropy/io/fits/hdu/table.py:337, in _TableBaseHDU.__init__(self, data, header, name, uint, ver, character_as_bytes)
    335     if future_ignore:
    336         keys = ', '.join(x + 'n' for x in sorted(future_ignore))
--> 337         warnings.warn("The following keywords are now recognized as special "
    338                       "column-related attributes and should be set via the "
    339                       "Column objects: {}. In future, these values will be "
    340                       "dropped from manually specified headers automatically "
    341                       "and replaced with values generated based on the "
    342                       "Column objects.".format(keys), AstropyDeprecationWarning)
    344 # TODO: Too much of the code in this class uses header keywords
    345 # in making calculations related to the data size.  This is
    346 # unreliable, however, in cases when users mess with the header
    347 # unintentionally--code that does this should be cleaned up.
    348 self._header['NAXIS1'] = self.data._raw_itemsize

File /usr/lib/python3.8/warnings.py:109, in _showwarnmsg(msg)
    105         if not callable(sw):
    106             raise TypeError("warnings.showwarning() must be set to a "
    107                             "function or method")
--> 109         sw(msg.message, msg.category, msg.filename, msg.lineno,
    110            msg.file, msg.line)
    111         return
    112 _showwarnmsg_impl(msg)

File ~/pyenvs/artxc/lib/python3.8/site-packages/astropy/logger.py:204, in AstropyLogger._showwarning(self, *args, **kwargs)
    201         break
    203 if mod_name is not None:
--> 204     self.warning(message, extra={'origin': mod_name})
    205 else:
    206     self.warning(message)

File /usr/lib/python3.8/logging/__init__.py:1458, in Logger.warning(self, msg, *args, **kwargs)
   1449 """
   1450 Log 'msg % args' with severity 'WARNING'.
   1451 
   (...)
   1455 logger.warning("Houston, we have a %s", "bit of a problem", exc_info=1)
   1456 """
   1457 if self.isEnabledFor(WARNING):
-> 1458     self._log(WARNING, msg, args, **kwargs)

File /usr/lib/python3.8/logging/__init__.py:1589, in Logger._log(self, level, msg, args, exc_info, extra, stack_info, stacklevel)
   1586         exc_info = sys.exc_info()
   1587 record = self.makeRecord(self.name, level, fn, lno, msg, args,
   1588                          exc_info, func, extra, sinfo)
-> 1589 self.handle(record)

File /usr/lib/python3.8/logging/__init__.py:1599, in Logger.handle(self, record)
   1592 """
   1593 Call the handlers for the specified record.
   1594 
   1595 This method is used for unpickled records received from a socket, as
   1596 well as those created locally. Logger-level filtering is applied.
   1597 """
   1598 if (not self.disabled) and self.filter(record):
-> 1599     self.callHandlers(record)

File /usr/lib/python3.8/logging/__init__.py:1661, in Logger.callHandlers(self, record)
   1659     found = found + 1
   1660     if record.levelno >= hdlr.level:
-> 1661         hdlr.handle(record)
   1662 if not c.propagate:
   1663     c = None    #break out

File /usr/lib/python3.8/logging/__init__.py:954, in Handler.handle(self, record)
    952 self.acquire()
    953 try:
--> 954     self.emit(record)
    955 finally:
    956     self.release()

File ~/pyenvs/artxc/lib/python3.8/site-packages/astropy/logger.py:548, in StreamHandler.emit(self, record)
    546     color_print(record.levelname, 'green', end='', file=stream)
    547 elif record.levelno < logging.ERROR:
--> 548     color_print(record.levelname, 'brown', end='', file=stream)
    549 else:
    550     color_print(record.levelname, 'red', end='', file=stream)

File ~/pyenvs/artxc/lib/python3.8/site-packages/astropy/utils/console.py:356, in color_print(end, *args, **kwargs)
    325 def color_print(*args, end='\n', **kwargs):
    326     """
    327     Prints colors and styles to the terminal uses ANSI escape
    328     sequences.
   (...)
    353         be printed after resetting any color or font state.
    354     """
--> 356     file = kwargs.get('file', _get_stdout())
    358     write = file.write
    359     if isatty(file) and conf.use_color:

File ~/pyenvs/artxc/lib/python3.8/site-packages/astropy/utils/console.py:123, in _get_stdout(stderr)
    120     return sys_stream
    122 # Our system stream is an atty and we're in ipython.
--> 123 ipyio_stream = _IPython.get_stream(stream)
    125 if ipyio_stream is not None and isatty(ipyio_stream):
    126     # Use the IPython console output stream
    127     return ipyio_stream

File ~/pyenvs/artxc/lib/python3.8/site-packages/astropy/utils/console.py:100, in _IPython.get_stream(cls, stream)
     98 @classmethod
     99 def get_stream(cls, stream):
--> 100     return getattr(cls.ipyio, stream)

AttributeError: module 'IPython.utils.io' has no attribute 'stdout'
```

### Steps to Reproduce

1. Read a fits table
2. Try to make a new fits table using the data and header in it.

```python
from astropy.io import fits
datahdu = fits.open('datatable.fits')[1]
newdatahdu = fits.BinTableHDU(data=datahdu.data.copy(), header=datahdu.header.copy())
```

### System Details

Linux-5.4.0-97-generic-x86_64-with-glibc2.29
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
Numpy 1.19.2
pyerfa 1.7.2
astropy 4.2.1
Scipy 1.5.2
Matplotlib 3.3.2

**Comment by pllim** [comment]
The code mentioned in traceback no longer exist. Can you please try to update astropy and see if you still get an error? Thanks!

**Comment by CTJChen** [comment]
Can confirm that the error messages disappeared after updating astropy to 5.0.1. I think that issue can occur with ipython 8+ and older astropy. Thanks for the suggestion!

**Comment by pllim** [comment]
Given 5.0 is the new long-term support release, we no longer have plans to update 4.x series. If upgrading is okay for you, please close this issue. Thanks!
