### ISSUE TITLE
``SkyCoord.realize_frame`` crashes when passed a representation

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2890]
According to the docs, `realize_frame` should take a representation:

```
Definition:  c1.realize_frame(self, representation)
Docstring:
Generates a new frame *with new data* from another frame (which may or
may not have data).

Parameters
----------
representation : BaseRepresentation
    The representation to use as the data for the new frame.
```

However if I try this it crashes:

```
In [65]: c1 = SkyCoord(1 * u.deg, 2 * u.deg)

In [66]: c2 = SkyCoord(1 * u.deg, 3 * u.deg)

In [67]: c1.realize_frame(c2.representation)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-68-3611222f5ea6> in <module>()
----> 1 c1.realize_frame(c2.representation)

/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9642-py3.4-macosx-10.8-x86_64.egg/astropy/coordinates/baseframe.py in realize_frame(self, representation)
    603         frattrs = dict([(nm, getattr(self, nm)) for nm in self.get_frame_attr_names()
    604                         if nm not in self._attr_names_with_defaults])
--> 605         return self.__class__(representation, **frattrs)
    606 
    607     def represent_as(self, new_representation, in_frame_units=False):

/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9642-py3.4-macosx-10.8-x86_64.egg/astropy/coordinates/baseframe.py in __new__(cls, *args, **kwargs)
    379             kwargs['frame'] = frame_name
    380             from .sky_coordinate import SkyCoord
--> 381             return SkyCoord(*args, **kwargs)
    382         else:
    383             return super(BaseCoordinateFrame, cls).__new__(cls)

/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9642-py3.4-macosx-10.8-x86_64.egg/astropy/coordinates/sky_coordinate.py in __init__(self, *args, **kwargs)
    132         # creating the internal self._sky_coord_frame object
    133         args = list(args)  # Make it mutable
--> 134         kwargs = self._parse_inputs(args, kwargs)
    135 
    136         # Set internal versions of object state attributes

/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9642-py3.4-macosx-10.8-x86_64.egg/astropy/coordinates/sky_coordinate.py in _parse_inputs(self, args, kwargs)
    224                 # along with any frame attributes like equinox or obstime which
    225                 # were explicitly specified in the coordinate object (i.e. non-default).
--> 226                 coord_kwargs = _parse_coordinate_arg(args[0], frame, units)
    227 
    228             elif len(args) <= 3:

/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9642-py3.4-macosx-10.8-x86_64.egg/astropy/coordinates/sky_coordinate.py in _parse_coordinate_arg(coords, frame, units)
    949 
    950     else:
--> 951         raise ValueError('Cannot parse coordinates from first argument')
    952 
    953     # Finally we have a list of values from which to create the keyword args

ValueError: Cannot parse coordinates from first argument
```

On the other hand, passing a coordinate object works:

```
In [67]: c1.realize_frame(c2)
Out[67]: <SkyCoord (ICRS): ra=8.0 deg, dec=3.0 deg>
```

If you're wondering why all the sudden bug reports, I'm trying to find a way to make a copy of a `SkyCoord` (that works with 0.4) for another package! (I think I have a solution).

cc @eteq @taldcroft

**Comment by bsipocz** [comment]
The code example above is still producing a traceback, though a different one, and ``c1.realize_frame(c2)`` and ``c1.realize_frame(c2.representation)`` are both doing the same now:

```
In [6]:  c1 = SkyCoord(1 * u.deg, 2 * u.deg)

In [7]: c2 = SkyCoord(1 * u.deg, 3 * u.deg)

In [8]: c1.realize_frame(c2.representation)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-3611222f5ea6> in <module>()
----> 1 c1.realize_frame(c2.representation)

/Users/bsipocz/munka/devel/astropy/astropy/coordinates/baseframe.py in realize_frame(self, representation)
    876                         for attr in self.get_frame_attr_names()
    877                         if attr not in self._attr_names_with_defaults])
--> 878         return self.__class__(representation, **frattrs)
    879 
    880     def represent_as(self, new_representation, in_frame_units=False):

/Users/bsipocz/munka/devel/astropy/astropy/coordinates/baseframe.py in __init__(self, *args, **kwargs)
    640                 else:
    641                     representation = self.representation
--> 642                 representation_data = representation(copy=copy, **repr_kwargs)
    643 
    644         if len(args) > 0:

TypeError: __init__() missing 1 required positional argument: 'lat'
```
