### ISSUE TITLE
Refactor WCSAxes to avoid calling Axes.contour to draw gridlines inside of drawing

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#12446]
The failure in https://github.com/astropy/astropy/issues/12431 was fixed in https://github.com/astropy/astropy/pull/12437 but the underlying issue was not really fixed and can be reproduced witth the following code which triggers two draws:

```python
import matplotlib.pyplot as plt
from astropy.wcs import WCS
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1, projection=WCS())
ax.grid(color='white', grid_type='contours')
fig.savefig('test.png')
fig.savefig('test.png')
```

This crashes with:

```
AttributeError: 'NoneType' object has no attribute 'dpi'
```

with Matplotlib 3.5.0rc1 (not previous versions).

I managed to boil this down to the minimal example shown in https://github.com/matplotlib/matplotlib/issues/21569 - as mentioned there by Matplotlib developers, calling ``ax.contour`` during drawing is a bad idea, and even more so removing the existing contour lines.

There are several long-term options I think at this point:

* Find a way to draw contours on-the-fly that doesn't require adding/removing artists from the axes and use that instead of ``ax.contour``. Unfortunately I think the contour-generating code in Matplotlib is private API (``matplotlib._contour``) so I'm not sure how we can do this. We could potentially come up with our own contour-drawing code which seems like a lot of effort.
* See if we can avoid the hack introduced in https://github.com/astropy/astropy/pull/7098 so that we can once again do things like update contour lines etc at the start of ``Axes.draw`` which I *think* would solve the issue. There are two sub-options here to investigate: making it so that all plot elements are regular artists that are added to the axes (I can't remember anymore why this wasn't the case but I feel like there was a good reason at the time!), or better handling the zorder for ticks etc internally in a way that doesn't require the hack.

This is a reasonably urgent issue as users might potentially run into issues when Matplotlib  3.5 is released, so in the mean time I am going to open a PR for a quick fix which is to remove any grid contour lines at the very start of drawing. But I think we do want to think about how to improve/refactor this long-term.

**Comment by QuLogic** [comment]
>     * Find a way to draw contours on-the-fly that doesn't require adding/removing artists from the axes and use that instead of `ax.contour`.

Note, I only meant that _changing_ what was drawn is bad. Because the list to draw is copied at the start o `Axes.draw`, adding something in your `draw`, explicity calling `draw` on it, and immediately removing it _may_ allow you to work around this, because you have in the end not changed what the Axes thinks is being drawn.

**Comment by astrofrog** [comment]
So the original bug here was fixed in https://github.com/astropy/astropy/pull/12447 but as noted in that PR the fix is not the optimal fix and we may need to think about refactoring to avoid this kind of issue, so keeping open.
