### ISSUE TITLE
[0,4,2] does not compile with wcslib-4.24

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#2976]
There is an [incompatible API change in wcslib 4.24](http://upstream-tracker.org/compat_reports/wcslib/4.23_to_4.24/abi_compat_report.html#High_Risk_Problems) that causes complilation failure and runtime problems (if compiled with 4.23, but started with 4.24). Unfortunately, wcslib did not increase the SONAME in 4.24 (probably since the change was on functions introduced only in 4.23), but it would be good to upgrade the interface and the internal wcslib to 4.24 ASAP.

**Comment by mdboom** [comment]
Just seeing this after vacation now -- just wanted to say I agree with the assessment here.  wcslib 4.23 was an unfortunate release, for which I am at least partially to blame.

**Comment by migueldvb** [comment]
I am getting this error when I try to build astropy 0.4.4 with wcslib 4.24:

```
astropy/wcs/src/wcslib_wrap.c:1699:14: error: too few arguments to function ‘wcscompare’
     status = wcscompare(
              ^
In file included from astropy/wcs/include/astropy_wcs/util.h:21:0,
                 from astropy/wcs/include/astropy_wcs/pyutil.h:9,
                 from astropy/wcs/include/astropy_wcs/wcslib_wrap.h:9,
                 from astropy/wcs/src/wcslib_wrap.c:8:
/usr/include/wcslib/wcs.h:1576:5: note: declared here
 int wcscompare(int cmp, double tol, const struct wcsprm *wcs1,
```

**Comment by mdboom** [comment]
@migueldvb: That doesn't surprise me.  wcslib 4.24 changed the API of wcscompare.  Therefore, the 0.4.x series must be used with wcslib 4.23 or earlier, and the 1.x series must be used with 4.24 or later.

**Comment by migueldvb** [comment]
OK, the CHANGES.rst in the 0.4.x branch says  `astropy now requires wcslib version 4.23 or later`. Should this sentence be changed for 0.4.5?

**Comment by embray** [comment]
Unless something major comes up I don't think there will be an 0.4.5.  If @mdboom agrees though that line could still be fixed.

**Comment by mdboom** [comment]
I have no problem with the documentation being updated.  It's unfortunate I said "or later" at the time, because I can't predict the future...

**Comment by olebole** [comment]
*If* there is a 0.4.5 (or any other pre-1 release), I would opt for updating the astropy internal wcs to 4.24 or later, and update the docu accordingly. 4.23 was just unfortunate, and should not live long.

**Comment by olebole** [comment]
I don't see a reason to keep this open anymore, so I am closing; if you feel it is still important, please re-open it.
