### ISSUE TITLE
ImportError when trying to import from astropy.tests.helper

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#7719]
This is fairly unexpected and must have broken recently. Here's what I tried to do:

```python
from astropy.tests.helper import enable_deprecations_as_exceptions
```

And here's the result:
```python
ImportError                               Traceback (most recent call last)
<ipython-input-1-dec8117bee17> in <module>()
----> 1 from astropy.tests.helper import enable_deprecations_as_exceptions

~/stsci/astropy/astropy/tests/helper.py in <module>()
     20     pass
     21
---> 22 from ..units import allclose as quantity_allclose  # noqa
     23 from ..utils.exceptions import (AstropyDeprecationWarning,
     24                                 AstropyPendingDeprecationWarning)

~/stsci/astropy/astropy/units/__init__.py in <module>()
     12
     13 from .core import *
---> 14 from .quantity import *
     15 from .decorators import *
     16

~/stsci/astropy/astropy/units/quantity.py in <module>()
     27 from ..utils.data_info import ParentDtypeInfo
     28 from .. import config as _config
---> 29 from .quantity_helper import (converters_and_unit, can_have_arbitrary_unit,
     30                               check_output)
     31

~/stsci/astropy/astropy/units/quantity_helper.py in <module>()
     14 from .core import (UnitsError, UnitConversionError, UnitTypeError,
     15                    dimensionless_unscaled, get_current_unit_registry)
---> 16 from .._erfa import ufunc as erfa_ufunc
     17
     18

~/stsci/astropy/astropy/_erfa/__init__.py in <module>()
      2 try:
      3     # The ERFA wrappers are not guaranteed available at setup time
----> 4     from .core import *
      5 except ImportError:
      6     if not _ASTROPY_SETUP_:

~/stsci/astropy/astropy/_erfa/core.py in <module>()
     35
     36 import numpy
---> 37 from . import ufunc
     38 from .ufunc import (dt_eraASTROM, dt_eraLDBODY, dt_pv,
     39                     dt_sign, dt_type, dt_ymdf, dt_hmsf, dt_dmsf)

ImportError: cannot import name 'ufunc'
```

**Update**: This appears to have been introduced by https://github.com/astropy/astropy/commit/ae1ed4273a9869fb27517ddeb5c77c4441068412

**Comment by drdavella** [comment]
Actually, it turns out that I just pulled without running `./setup.py develop` again afterwards. Rerunning  `develop` fixed my issue.

Sorry for the noise.
