### ISSUE TITLE
`units.quantity_input` with annotated `Quantity` type hint in a `Union` causes error

### ISSUE THREAD

**Issue by vandalt** [astropy/astropy#17017]
### Description

Hi!

I'm not sure if this is a bug report or feature request for unsupported use case.

I have a case where an argument could be either a Quantity or a string that will later be converted to quantity. I tried type hinting with `Union[Quantity["angle"], str]`, but this causes the error shown below when using a string as the argument. See the minimal example below for the error when using the `units.quantity_input` decorator.

My understanding of the issue is it comes from [the QuantityInput decorator](https://github.com/astropy/astropy/blob/e5fa5cb4eb48050ba49ead981a19fd07da3e8619/astropy/units/decorators.py?plain=1#L256): non-quantity parts of the Union are set to False and then dropped from `valid_targets` before the decorator performs a check on the quantity. Then if the argument is not a quantity the check will fail because the string has no units.

Thank you

### Expected behavior

The behavior I would have expected is that non-quantity types are considered as part of the `Union` when validating the input. I could see two ways to fix/support this:

1. Recognize other types parts of `Union` and check if the argument `isinstance` of one of them when it's not a `Quantity`
2. When the type is a union, just drop validation, as would be the case with a non-annotated quantity. I think this is less desirable as it could let pass wrong units unexpectedly for users.

I could try implementing one of these if you think it is a good way forward.

### How to Reproduce

1. Install latest main branch from github
2. Run the snippet below
3. Get the error below the snippet

The code:

```python
from typing import Union

import astropy.units as u
from astropy.units import Quantity


@u.quantity_input
def afun(length_or_str: Union[Quantity["length"], str]):
    print(f"Worked with {length_or_str}")

afun(1 * u.m)  # Works
afun("1m")  # Fails
```

The error:

```python
Worked with 1.0 m
Traceback (most recent call last):
  File "/home/vandal/repos/astro/astropy/astropy/units/decorators.py", line 69, in _validate_arg_value
    if arg.unit.is_equivalent(allowed_unit, equivalencies=equivalencies):
       ^^^^^^^^
AttributeError: 'str' object has no attribute 'unit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vandal/repos/astro/astropy/quantity_input_minimal.py", line 12, in <module>
    afun("1m")  # Fails
    ^^^^^^^^^^
  File "/home/vandal/repos/astro/astropy/astropy/units/decorators.py", line 298, in wrapper
    _validate_arg_value(
  File "/home/vandal/repos/astro/astropy/astropy/units/decorators.py", line 78, in _validate_arg_value
    raise TypeError(
TypeError: Argument 'length_or_str' to function 'afun' has no 'unit' attribute. You should pass in an astropy Quantity instead.
```

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
# Paste the result here
platform
--------
platform.platform() = 'Linux-6.10.9-arch1-2-x86_64-with-glibc2.40'
platform.version() = '#1 SMP PREEMPT_DYNAMIC Tue, 10 Sep 2024 14:37:32 +0000'
platform.python_version() = '3.12.5'

packages
--------
astropy              7.0.0.dev436+g3b88b55dfc
numpy                2.0.0
scipy                1.14.0
matplotlib           3.9.1
pandas               2.2.2
pyerfa               2.0.1.4
```

**Comment by pllim** [comment]
@nstarman and @mhvk , any advice? Thanks!

**Comment by nstarman** [comment]
That sounds like a tricky one! we would have to scan over the Union and build a parser that first filters, then applies any quantity conversion.

**Comment by mhvk** [comment]
Indeed. I think it also goes a bit beyond what `quantity_input` is meant to provide: it very much insists on `Quantity` input, not something convertible to it. I think one may be better off just checking in the function itself...

**Comment by vandalt** [comment]
Thaks for the feedback!

Just for context, the use case where I encountered this was adding type hints to Astroplan (see [this PR](https://github.com/astropy/astroplan/pull/593)). I think for "legacy" code like that the functionality I described would be useful to keep the `quantity_input` checks while adding `Quantity` type hints with informative units/physical type information.

The implementation I was thinking of would not involve checking type conversions. It would only allow `quantity_input` to not fail on, for example `Union[Quantity["length"], str]`. `str` could be any other type here, and not necessarily convertible to a Quantity. The goal would be to cover the generic case where the code allows various types of inputs. If the argument is a quantity it would be validated, but if it is not, the only check would be that it's an instance of other types in the Union. When the author includes a Union annotation with these types, it's probably reasonable to assume they have the relevant conversions/use cases covered inside the function.

I have an implementation that I could submit as a draft PR if you think it would be worth discussing more. The git diff is small so I'm putting it below if you want to have a quick look.

Otherwise I think a mention of this unsupported use-case in the annotated Quantity docs or `quantity_input` docs might be helpful. Happy to submit a PR with that as well.

Thanks!


<details>

<summary>The git diff of the draft implementation</summary>

```diff
diff --git a/astropy/units/decorators.py b/astropy/units/decorators.py
index e56e576000..0c6e3cc56f 100644
--- a/astropy/units/decorators.py
+++ b/astropy/units/decorators.py
@@ -40,7 +40,13 @@ def _get_allowed_units(targets):
 
 
 def _validate_arg_value(
-    param_name, func_name, arg, targets, equivalencies, strict_dimensionless=False
+    param_name,
+    func_name,
+    arg,
+    targets,
+    equivalencies,
+    strict_dimensionless=False,
+    type_targets=None,
 ):
     """
     Validates the object passed in to the wrapped function, ``arg``, with target
@@ -64,6 +70,15 @@ def _validate_arg_value(
         elif isinstance(arg, np.ndarray) and np.issubdtype(arg.dtype, np.number):
             return
 
+    # If non-quatity types are allowed and the arg matches one of them
+    #   allow it to pass through
+    if (
+        type_targets is not None
+        and not hasattr(arg, "unit")
+        and isinstance(arg, tuple(type_targets))
+    ):
+        return
+
     for allowed_unit in allowed_units:
         try:
             if arg.unit.is_equivalent(allowed_unit, equivalencies=equivalencies):
@@ -76,6 +91,7 @@ def _validate_arg_value(
                 error_msg = "no 'unit' attribute"
 
             raise TypeError(
+                # TODO: Update message with type_targets?
                 f"Argument '{param_name}' to function '{func_name}'"
                 f" has {error_msg}. You should pass in an astropy "
                 "Quantity instead."
@@ -116,15 +132,19 @@ def _parse_annotation(target):
     if origin is T.Union:
         return [_parse_annotation(t) for t in T.get_args(target)]
     elif origin is not T.Annotated:  # can't be Quantity[]
+        if isinstance(target, type):
+            return target
         return False
 
     # parse type hint
     cls, *annotations = T.get_args(target)
+    # TODO: fix this one as well
     if not issubclass(cls, Quantity) or not annotations:
         return False
 
     # get unit from type hint
     unit, *rest = annotations
+    # TODO: fix this one as well
     if not isinstance(unit, (UnitBase, PhysicalType)):
         return False
 
@@ -287,11 +307,14 @@ class QuantityInput:
                 #    are not strings or subclasses of Unit. This is to allow
                 #    non unit related annotations to pass through
                 if is_annotation:
+                    type_targets = [t for t in valid_targets if isinstance(t, type)]
                     valid_targets = [
                         t
                         for t in valid_targets
                         if isinstance(t, (str, UnitBase, PhysicalType))
                     ]
+                else:
+                    type_targets = None
 
                 # Now we loop over the allowed units/physical types and validate
                 #   the value of the argument:
@@ -302,6 +325,7 @@ class QuantityInput:
                     valid_targets,
                     self.equivalencies,
                     self.strict_dimensionless,
+                    type_targets=type_targets,
                 )
 
             if self.equivalencies:
diff --git a/astropy/units/tests/test_quantity_decorator.py b/astropy/units/tests/test_quantity_decorator.py
index 8eb4ade0c7..d8b9f4d828 100644
--- a/astropy/units/tests/test_quantity_decorator.py
+++ b/astropy/units/tests/test_quantity_decorator.py
@@ -487,3 +487,20 @@ def test_annotated_not_unit():
     assert myfunc(1) == 1
     assert myfunc(1 * u.m) == 1 * u.m
     assert myfunc(1 * u.s) == 1 * u.s
+
+
+def test_union_with_type():
+    @u.quantity_input
+    def myfunc(x: u.Quantity["length"] | str):  # noqa: F821
+        return x
+
+    assert myfunc(1 * u.m) == 1 * u.m
+    assert myfunc("1m") == "1m"
+    with pytest.raises(
+        TypeError,
+        match=(
+            "Argument 'x' to function 'myfunc' has no 'unit' attribute. "
+            "You should pass in an astropy Quantity instead."
+        ),
+    ):
+        x = myfunc(5.0)
```

</details>

**Comment by mhvk** [comment]
That diff does not seem unreasonable, but on anything typing related I trust @nstarman's opinion more. Let me also pin @Cadair, who I think wrote `quantity_input` originally.

**Comment by eerovaher** [comment]
Instead of trying to improve `quantity_input`, we should instead try to make `astropy` more friendly towards type checkers. If we succeed in doing that then users could perform type checking with a dedicated static type checker or a dedicated runtime type checker. [Code compiled with mypyc will also contain runtime type checks.](https://mypyc.readthedocs.io/en/latest/differences_from_python.html#runtime-type-checking)

I understand that `astropy` cannot really be used together with type checkers right now or any time soon, so we shouldn't remove support for runtime type checking that `quantity_support` already offers quite yet, but adding more functionality to it is not moving in the right direction.

**Comment by Cadair** [comment]
I think quantity_input is orthogonal to type checking, the runtime guarantees it makes both on input and output are what is useful in my opinion. While stuff like mypyc is cool, many people aren't going to want that or other more generic runtime type checking to check and convert units. Also `quantity_input` used function annotations "before they were cool" for type checking anyway :stuck_out_tongue:.

I am not sure I like the idea of allowing non-quantity types through `quantity_input`, it feels weird to me, and thinking about how to document it puts me off due to the complexity. I am open to be persuaded though.

**Comment by vandalt** [comment]
I think even a quick one-sentence mention in the [multiple annotations](https://docs.astropy.org/en/latest/units/type_hints.html#multiple-annotations) sections would be helpful, and/or a short mention that union of annotated quantities and other types is not supported when `quantity_input` is used, in the [`quantity_input` docs](https://docs.astropy.org/en/latest/api/astropy.units.quantity_input.html#astropy.units.quantity_input).

In the  I had not anticipated this incompatibility after reading these two documentation pages, updated a whole code base using annotated-type hints, and then realized this would make some union type hints compatible with quantity input (which I was using explicitly for some, but not all quantities in my inputs), so I had to remove the annotation from several type hints.

**Comment by mhvk** [comment]
> I am not sure I like the idea of allowing non-quantity types through `quantity_input`, it feels weird to me, and thinking about how to document it puts me off due to the complexity. I am open to be persuaded though.

Right now, `quantity_input` checks that an argument has a unit equivalent to what is required, but one could also think of a version/possibility that does the equivalent of `u.Quantity(arg, desired_unit)`. This would ensure an argument is a `Quantity`, check and convert the units for input `Quantity`, effectively set an assumed unit for arrays, and would work for `str` input. I think that would be fairly useful, but really is a different beast -- see #7368.
