### PR TITLE
Added instructions for installing Astropy into CASA

### PR DESCRIPTION
**Pull request by astrofrog**
This might be a somewhat controversial addition, but I think this is a common enough use case that it's worth mentioning here. There are various hacks in different places for installing packages into CASA, but the easiest way (if the user has write access to CASA, e.g. on MacOS X) is the one outlined here (tested with CASA 4.2.2).

[@keflavich @trhunter - do you agree this is the easiest way at the moment?]

### CODE REVIEW

File: docs/install.rst [hunk 1]
```diff
@@ -374,6 +374,19 @@ __ https://gist.github.com/embray/6042780#file-win_register_python-py
...
+
+If you want to be able to use Astropy inside `CASA
+<https://casa.nrao.edu/>`_, the easiest way is to run pip from inside CASA.
+Start up ``casapy`` as normal, and type::
+
+    CASA <2>: import pip
+
+    CASA <3>: pip.main(['install', 'astropy', '--user'])
+
+Then close CASA and open it up again, and you should be able to import CASA.
```
Comment (MSeifert04) [inline docs/install.rst]: "you should be able to import CASA." I'm not familiar with CASA but why import CASA after opening CASA? Do you mean import astropy?

Comment (astrofrog) [inline docs/install.rst]: Oops, typo

**Comment by pllim** [comment]
Isn't this more appropriate on the CASA-side? Once you cross this line, what about all the other distributions out there?

**Comment by pllim** [comment]
What if CASA changes the next version? Are we supposed to keep up with they are doing?

**Comment by astrofrog** [comment]
@pllim - I think this works for all CASA versions, and these instructions should be pretty robust (we're just using pip directly from inside IPython).

> Isn't this more appropriate on the CASA-side? Once you cross this line, what about all the other distributions out there?

This is why I said it was controversial :) I don't think the CASA developers want to encourage people installing third-party packages into CASA, so I don't think they will put this on the CASA website. I know that this is a common question, and I don't think there's any harm in including this here. But I'll go with the majority opinion! :)

File: docs/install.rst [hunk 2]
```diff
@@ -374,6 +374,21 @@ __ https://gist.github.com/embray/6042780#file-win_register_python-py
 
 .. _builddocs:
```
Comment (mhvk) [inline docs/install.rst]: This label should be kept with its section header!

**Comment by mhvk** [comment]
While I share @pllim's concern about setting a precedent, I think it is fine to have instructions for help in installing in astronomy-specific distributions.

File: docs/install.rst (hunk 2 above)
Comment (astrofrog) [inline docs/install.rst]: Oops, fixed!

**Comment by mhvk** [comment]
p.s. Once we merge this, I would suggest writing the CASA people and pointing out to them that at least some of their users do want to use astropy, that this is quite easy to do, and ask whether they can also have a note on their website about integration with other packages (do they have numpy?).

File: CHANGES.rst [hunk 3]
```diff
@@ -486,7 +486,7 @@ Bug Fixes
 Other Changes and Additions
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
-- Nothing changed yet.
+- Added instructions for installing Astropy into CASA.
```
Comment (bsipocz) [inline CHANGES.rst]: Generally we don't add changelog entries for docs enhancement, do we?

Comment (mhvk) [inline CHANGES.rst]: My sense is that here it is useful: someone who is using astropy but not within CASA may look at what changed may now realise this is possible; very unlikely they would find it in the documentation if they had already concluded it was "hard".

Comment (bsipocz) [inline CHANGES.rst]: OK, good point. 
I've just assumed people don't browse changelogs unless they have a bug or problem.

**Comment by astrofrog** [comment]
Hmm apparently some CASA installations don't have pip, investigating

**Comment by keflavich** [comment]
@astrofrog did pip get installed by [casa-python](https://github.com/radio-astro-tools/casa-python)?

**Comment by astrofrog** [comment]
Well, I didn't think so because I started from what I thought was a clean version of CASA. I'll double check and will amend the instructions if needed.

**Comment by keflavich** [comment]
Did you remove your `~/.casa` directory to get a "clean" version?  I think CASA will import from that directory (or some subdirectory) by default if it exists.

**Comment by astrofrog** [comment]
@keflavich - yeah, I just found that leftover directory, so I need to work on this more. So one solution is to do:

```
In [6]: from setuptools.command import easy_install

In [7]: easy_install.main(['pip'])
```

first, but the issue is I can't figure out how to pass the ``--user`` flag (passing it as the second item in the list doesn't work). I'll look into it some more

**Comment by astrofrog** [comment]
@keflavich - does this look better now?

**Comment by keflavich** [comment]
@astrofrog - yes, looks good.  I'll test it next time I have a fresh system to work with.

Could we add something extra, like: "Any astropy affiliated package can be installed the same way, e.g. the [spectral-cube](spectral-cube.rtfd.org) package that is intended to work directly with CASA."

**Comment by astrofrog** [comment]
@keflavich - done!

**Comment by astrofrog** [comment]
I've tried this on various systems, and there are issues with missing include files. I'll report this upstream to the CASA developers.

**Comment by pllim** [comment]
@astrofrog 

>  I don't think the CASA developers want to encourage people installing third-party packages into CASA

Would they respond favorably to your report? :smile:

**Comment by trhunter** [comment]
Yes, I think they would.  What would likely happen is I would open a CASA ticket to request the desired behavior.  But I should say here that the way I install astropy into CASA is by using the casa-config script, which should be distributed in the rpm and tarball.

bash$ wget --quiet https://pypi.python.org/packages/source/a/astropy/astropy-1.1.2.tar.gz
bash$ tar zxf astropy-1.1.2.tar.gz 
bash$ cd astropy-1.1.2
bash$ casa-config --exec ./setup.py install --user 

where the --user is only needed if you do not have root on the installation.

**Comment by astrofrog** [comment]
@trhunter - interestingly, if I try your method I end up with the same issues, so I think the issues I'm running into are unrelated to the installation method. With CASA 4.6.0 on Fedora, I see:

```
gcc -pthread -fno-strict-aliasing -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -DNDEBUG -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fPIC -I/software/casa-release-4.6.0-el6/include/python2.7 -c astropy/_compiler.c -o build/temp.linux-x86_64-2.7/astropy/_compiler.o
astropy/_compiler.c:1:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
```

Basically the whole ``casa-release-4.6.0-el6/include`` folder is missing. Which version of CASA are you using?

**Comment by trhunter** [comment]
Ah, yes.  This method worked in casa 4.4, but was broken in 4.5.2 and 4.6.  In late March, I encountered the same error as you and opened a ticket (CAS-8460) which was right before the 4.6.0 release.  It is definitely fixed in 4.7.30 onward (April 14), but it looks like the fix missed the 4.6.0 release (April 2).  It has been fixed in the NRAO/CV installs of 4.6.0, but because there has been no larger bugs identified yet, there has been no patch release (i.e. no 4.6.1).  Sorry for the confusion.  If you want, you can try it with the latest 4.7 stable at https://svn.cv.nrao.edu/casa/distro/linux/stable/el6/

**Comment by astrofrog** [comment]
@trhunter - thanks for clarifying. So I think the solution will simply be to say that astropy cannot be installed in CASA 4.5 and 4.6, but should work in 4.4 and 4.7+? (maybe 4.3, but I have to try it out). I think our methods should both work, and I prefer using pip if possible to avoid having to type out the URL .

**Comment by astrofrog** [comment]
@trhunter - interestingly my installation method works for 4.5.2 and 4.5.3, so it's just 4.6.0 that doesn't work. I've added a note about which versions the installation should work with.

**Comment by keflavich** [comment]
@trhunter now that this is demonstrated to work, might it be possible to get astropy compilation/installation included as part of the release testing process?

**Comment by eteq** [comment]
I'm not familiar enough with the CASA infrastructure to say how likely it is to get this in on the CASA side... But FWIW I'd say if we think that's somewhat uncertain, it's fine to have this in here.  I agree with @pllim that it's not ideal, and in a perfect world we wouldn't need to do this... But as we all know astro software is a far from perfect world ;)

**Comment by astrofrog** [comment]
Ok, I'm going to go ahead and merge this, and we can remove it if it gets added on the CASA side - hopefully this should be a good compromise.

**Comment by keflavich** [comment]
@astrofrog - is it possible to do this from a command-line script?  A non-interactive approach is necessary if we want to install astropy & other packages into CASA on travis

**Comment by astrofrog** [comment]
@keflavich - you could write a script for each of the three steps, and run with casapy -c script.py?

**Comment by keflavich** [comment]
@astrofrog: tried this: https://github.com/keflavich/spectral-cube/blob/0bf0ffce461001f836c8fa8e4071e87dc8f36762/.casa_setup.py which resulted in no output from travis: https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/132583913#L543 but apparently failed to install astropy: https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/132583913#L704

Any ideas?  Do you (or @trhunter) know exactly what `casa-config --exec` is doing?  Is it running the code as a shell script or from within a python environment?  Since `setup.py` fails but `./setup.py` succeeds, I guess it might be a shell script...?

**Comment by keflavich** [comment]
@astrofrog I've tried this further on a test machine using various non-interactive approaches (using `casa-config --exec` and `casa -c`), and it hasn't worked.

**Comment by astrofrog** [comment]
@keflavich - I'm not sure what's going on, but you'll definitely need to split:

https://github.com/keflavich/spectral-cube/blob/0bf0ffce461001f836c8fa8e4071e87dc8f36762/.casa_setup.py

into two scripts because you should quit between the easy_install and pip part.

**Comment by keflavich** [comment]
yeah, did that:
https://github.com/keflavich/spectral-cube/blob/CASA_bintable_fixes/.install_pip.py
https://github.com/keflavich/spectral-cube/blob/CASA_bintable_fixes/.install_astropy.py

Doing `casa-config --exec ./.install_pip.py` quits instantly, with no output, suggesting that it's not actually executing any code.  `casa -c 'execfile(".install_pip.py")'` seems to have worked, though...

**Comment by keflavich** [comment]
followup: installing astropy fails with
```
    gcc -pthread -fno-strict-aliasing -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -DNDEBUG -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fPIC -I/scratch/aginsbur/casa/casa-release-4.6.0-el6/include/python2.7 -c astropy/_compiler.c -o build/temp.linux-x86_64-2.7/astropy/_compiler.o
    astropy/_compiler.c:1:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/scratch/aginsbur/casa/casa-release-4.6.0-el6/lib/casa/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-acYE95/astropy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3Dukwi-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-acYE95/astropy/
leaving casapy...
```

which might be related to CASA 4.5/4.6 not including the appropriate python header files?

**Comment by astrofrog** [comment]
@keflavich - ah, we don't support CASA 4.5 for precisely this reason. It was supposed to be fixed in the latest stable version of CASA 4.6, but are you finding that this is not the case?

**Comment by astrofrog** [comment]
@keflavich - can you try with the latest 'stable' instead of the latest 'release' version?

**Comment by trhunter** [comment]
It was the 4.6.0 public release that did not include the header files.   This method should work with the recent stables (>= 4.7.30).

**Comment by astrofrog** [comment]
@trhunter - when I did this PR, it worked with the latest 4.6 stables (>=4.6.30) though. But could it be those changes weren't in time for the final 4.6 release?

**Comment by keflavich** [comment]
It works with casa-stable-4.7.64 using my scripts

**Comment by keflavich** [comment]
When I try installing other packages (e.g., spectral-cube), other failures appear:
```
ImportError: No module named _build_utils.apple_accelerate
```
Full traceback here:
http://pastebin.com/xSTvwWnZ

**Comment by astrofrog** [comment]
@keflavich - the issue is that you should **never** upgrade Numpy inside CASA, or everything will blow up. However, it looks like in the gist you sent, Numpy is getting included. Bad times. 💥

**Comment by keflavich** [comment]
Right; the upgraded numpy should be `--user` installed, right?  But it seems that `--user` has no effect; the packages are getting installed directly into `casa-release-4.6.0-el6/lib/python2.7/site-packages`.  With [casa-python](https://github.com/radio-astro-tools/casa-python), packages were installed into `~/.casa/...` - is this the better approach?

**Comment by astrofrog** [comment]
@keflavich - the real solution is just to prevent Numpy from getting installed unfortunately. Is spectral-cube the package that requires a recent Numpy?

**Comment by keflavich** [comment]
yes.  `spectral-cube` has many functions that rely on a recent numpy, specifically the various `nan`-ufuncs

**Comment by astrofrog** [comment]
@keflavich - I don't know if it's possible to have two versions of Numpy installed/used at the same time (even if --user worked, it would mean all packages would start to use that version), so I think you're stuck unless CASA update Numpy?

**Comment by keflavich** [comment]
@astrofrog I thought we had successfully set up previous installations such that CASA used its own internal numpy for most things but other installed programs used whatever numpy they were compiled against in the user directory.  I don't know if that makes sense, but I'm fairly confident I've had numpy user installations without any conflict with CASA.

@astrofrog, @trhunter: are there any CASA tasks we can run as tests that would fail with newer versions of numpy to check this?

**Comment by keflavich** [comment]
On travis, I'm still getting a missing `Python.h` error when installing astropy into casa: https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/134961278#L1555

**Comment by astrofrog** [comment]
@keflavich - which version of CASA is this?

**Comment by keflavich** [comment]
[casa-monthly-4.7.16](https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/134961278#L316)

**Comment by astrofrog** [comment]
@keflavich - can you try the latest stable?

**Comment by keflavich** [comment]
Huh, yeah, [casa-stable-4.7.59](https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/134961280#L316) [worked](https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/134961280#L594).... so there seems to be a regression in the monthlies?

**Comment by keflavich** [comment]
oh, no, the stable is more recent than the monthly.  I don't think I understand how CASA versioning works.

**Comment by astrofrog** [comment]
@keflavich - I really don't either!

**Comment by astrofrog** [comment]
I think 'stable' means 'development version'. Confusing, eh?

**Comment by keflavich** [comment]
Aye.  Apparently, then, the [bug reported above](https://github.com/astropy/astropy/pull/4840#issuecomment-218183361) was only fixed since the last "monthly"

**Comment by trhunter** [comment]
Maybe I can help.  casa-stable simply means a development version (i.e. one of the daily casa-test versions) that has passed the regular regression tests.  To my knowledge, 'monthly' is nothing more than an occasional relabelling of a 'stable'.  We do not refer to any 'monthly' version in our internal testing, and frankly I thought it there was a plan to discontinue these.

**Comment by keflavich** [comment]
@trhunter thanks.  "monthly" sounded in my head like "daily" which is kind of like "dev", though that's not a correct association.  `casa-stable` appears to be analogous to `astropy/master`.  In any case, I think I'm really really close to getting a test to actually run....

**Comment by keflavich** [comment]
I'm still stuck on the numpy version issues in https://github.com/radio-astro-tools/spectral-cube/pull/312.  It's possible that spectral-cube (and many other affiliated packages, and maybe some utilities within astropy) won't work with CASA.
