### PR TITLE
ENH: fix compatibility with numpy 1.23

### LINKED ISSUE #12534: BUG: astropy.units fails to import with numpy 1.23.0dev
### Description

There is an incompatibility in astropy.units + numpy 1.23 which I believe is trivial to fix

### Expected behavior
Success

### Actual behavior
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/robcleme/.pyenv/versions/amical_tmp/lib/python3.10/site-packages/astropy/units/__init__.py", line 17, in <module>
    from .quantity import *
  File "/Users/robcleme/.pyenv/versions/amical_tmp/lib/python3.10/site-packages/astropy/units/quantity.py", line 32, in <module>
    from .quantity_helper import (converters_and_unit, can_have_arbitrary_unit,
  File "/Users/robcleme/.pyenv/versions/amical_tmp/lib/python3.10/site-packages/astropy/units/quantity_helper/__init__.py", line 10, in <module>
    from . import helpers, function_helpers
  File "/Users/robcleme/.pyenv/versions/amical_tmp/lib/python3.10/site-packages/astropy/units/quantity_helper/function_helpers.py", line 126, in <module>
    np.asscalar, np.alen,
  File "/Users/robcleme/.pyenv/versions/amical_tmp/lib/python3.10/site-packages/numpy/__init__.py", line 315, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'. Did you mean: 'isscalar'?
```

### Steps to Reproduce

1.
```
pip install git+https://github.com/numpy/numpy.git
```
2.
```
pip install -U -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy
```

```python
import astropy.units
```

### System Details
No relevant

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description
Fixes #12534
This is not necessarily sufficient to fix compatibility with numpy 1.23 completely but it should at least address the problem I stumbled upon.

for reference the breaking change upstream is from https://github.com/numpy/numpy/pull/20414

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Do the proposed changes actually accomplish desired goals?
- [ ] Do the proposed changes follow the [Astropy coding guidelines](https://docs.astropy.org/en/latest/development/codeguide.html)?
- [ ] Are tests added/updated as required? If so, do they follow the [Astropy testing guidelines](https://docs.astropy.org/en/latest/development/testguide.html)?
- [ ] Are docs added/updated as required? If so, do they follow the [Astropy documentation guidelines](https://docs.astropy.org/en/latest/development/docguide.html#astropy-documentation-rules-and-guidelines)?
- [ ] Is rebase and/or squash necessary? If so, please provide the author with appropriate instructions. Also see ["When to rebase and squash commits"](https://docs.astropy.org/en/latest/development/when_to_rebase.html).
- [ ] Did the CI pass? If no, are the failures related? If you need to run daily and weekly cron jobs as part of the PR, please apply the `Extra CI` label.
- [ ] Is a change log needed? If yes, did the change log check pass? If no, add the `no-changelog-entry-needed` label. If this is a manual backport, use the `skip-changelog-checks` label unless special changelog handling is necessary.
- [ ] Is a milestone set? Milestone must be set but `astropy-bot` check might be missing; do not let the green checkmark fool you.
- [ ] At the time of adding the milestone, if the milestone set requires a backport to release branch(es), apply the appropriate `backport-X.Y.x` label(s) *before* merge.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
I don't know if this warrants a changelog entry, please tell me if I need to write one.

**Review by mhvk — APPROVED** [review]
Thanks very much for noticing that and sending the fix!!  It looks all good. We should back-port this.

**Comment by mhvk** [comment]
The numpy-dev job passed, which included the numpy commit that removed the deprecated functions, so this PR is tested also for that.
