### PR TITLE
Make astropy.wcs.get_include raise an exception when astropy was built against system WCSLIB

### LINKED ISSUE #20045: BUG: wcsapi_test.c cannot find wcsconfig.h in exotic archs
Example log: https://github.com/astropy/astropy/actions/runs/28957163984/job/85919083339

7 errors

```
In file included from wcsapi_test.c:10:
  .../astropy/wcs/include/astropy_wcs/astropy_wcs_api.h:4:10: fatal error: wcsconfig.h:
  No such file or directory
      4 | #include "wcsconfig.h"
        |          ^~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/s390x-linux-gnu-gcc' failed with exit code 1
```

Caused by https://github.com/astropy/astropy/pull/19971

### PR DESCRIPTION
**Pull request by astrofrog**
When astropy it built against system WCSLIB, we don't include all the header files so ``get_include()`` doesn't work properly. This has never worked, so it makes sense to just raise an exception rather than try and find a way to make it work.

Fixes https://github.com/astropy/astropy/issues/20045 (to be clear this is not a new issue/regression, it's just that we were not testing it before)

### CODE REVIEW

**Comment by astrofrog** [comment]
The failures are unrelated, this is ready for review

File: astropy/wcs/tests/extension/test_extension.py [hunk 1]
```diff
@@ -69,6 +69,13 @@
 
 @pytest.fixture(scope="module")
 def wcsapi_test(tmp_path_factory):
+    try:
+        get_include()
+    except NoWcslibHeadersError as exc:
```
Comment (pllim) [inline astropy/wcs/tests/extension/test_extension.py]: I feel like this might miss cases where the includes are missing because of an actual bug. Can't we check for  `ASTROPY_USE_SYSTEM...` value to decide if we are indeed trying to grab system wcslib or not?

https://github.com/astropy/astropy/blob/96855a88aefdb4b43731b40926d18dc1c0dc043f/.github/workflows/ci_cron_weekly.yml#L189

**Comment by pllim** [comment]
linkcheck and devdeps failures are definitely unrelated.

~Can't quite tell with the Windows wheels, so I will run on `main` to see.~ OK, Windows wheels failures also unrelated. 😩 https://github.com/astropy/astropy/actions/runs/28995926024 (on main)

File: astropy/wcs/tests/extension/test_extension.py (hunk 1 above)
Comment (astrofrog) [reply astropy/wcs/tests/extension/test_extension.py]: Fixed

**Comment by pllim** [comment]
Thanks! LGTM but I will wait for Extra CI to finish before approving.

**Review by pllim — APPROVED** [review]
Failures are unrelated.  You are a 🧞 as usual!
